window._da_=window._da_||[];_da_['da_websiteId']='57793';_da_['da_anonymiseIP']=_da_['da_anonymiseIP']||false;_da_['da_account_flags']=0;_da_['da_account_flags_orig']=0;_da_['da_sessionId_e']='C05A1088F80BAE80CBFDAA136386E2F71A';_da_['da_leadId_e']='F36923BBEC4BEA1B5EACBB992184A8FCA9';_da_['da_fixedElementSelector']=_da_['da_fixedElementSelector']||'div.ht-wrapper-inner.-wrapper-cta > form.ht-form.-form-search > div.partial.-left';_da_['da_interactionSelector']=_da_['da_interactionSelector']||'a,input[type=submit],input[type=button]';_da_['da_personalDataSelector']=_da_['da_personalDataSelector']||'[data-di-mask]';_da_['da_unmaskFieldSelector']=_da_['da_unmaskFieldSelector']||'[data-di-unmask-field]';_da_['da_formErrorSelector']=_da_['da_formErrorSelector']||'';_da_['da_dnsRecord']='';_da_['da_proxyHost']='';_da_['da_sessCookieFlags']=0;_da_['da_leadCookieFlags']=0;_da_['da_formCollection']=0;
_da_["domains"] = ["myhometouch.com","www.myhometouch.com"];_da_["intScripts"] = function(){};_da_["formTitleCallback"] = function(form){if (!this.isEmpty(form.getAttribute('data-di-form-id'))) { return form.getAttribute('data-di-form-id'); } else if (!this.isEmpty(form.getAttribute('name'))) { return form.getAttribute('name'); } else if (!this.isEmpty(form.getAttribute('id'))) { return form.getAttribute('id'); } return '';};_da_["fieldTitleCallback"] = function(field){if (field.parentNode && field.parentNode.tagName.toUpperCase() === 'LABEL') { return this.Sizzle.getText(field.parentNode); } if (!this.isEmpty(field.id)) { var labelList = this.Sizzle('label[for=\''+field.id+'\']'); if (labelList.length) { return this.Sizzle.getText(labelList[0]); } } if (!this.isEmpty(field.getAttribute('data-di-field-id'))) { return field.getAttribute('data-di-field-id'); } if (!this.isEmpty(field.id)) { return field.id; } return field.name;};_da_["da_autoFragmentTrack"] = true;_da_["da_autoQueryTrack"] = true;_da_["da_maskEmail"] = false;_da_["da_maskSSN"] = false;_da_["da_frameRate"] = 5;_da_["da_resourceRate"] = 1;_da_["da_minResourceSize"] = 1000;_da_["da_fragmentPattern"] = "^#/.*";_da_['da_ignoreFieldSelector']=_da_['da_ignoreFieldSelector']||'[data-di-field-ignore]';_da_['da_canvasSelector']=_da_['da_canvasSelector']||'';_da_['accountNumber']='13169';(function(a){function b(a,b,n,c){try{var e,f,d,h,p,q,g,I=b&&b.ownerDocument,R=b?b.nodeType:9;n=n||[];if("string"!==typeof a||!a||1!==R&&9!==R&&11!==R)return n;if(!c&&((b?b.ownerDocument||b:S)!==A&&aa(b),b=b||A,M)){if(11!==R&&(p=za.exec(a)))if(e=p[1])if(9===R)if(d=b.getElementById(e)){if(d.id===e)return n.push(d),n}else return n;else{if(I&&(d=I.getElementById(e))&&ga(b,d)&&d.id===e)return n.push(d),n}else{if(p[2])return ba.apply(n,b.getElementsByTagName(a)),n;if((e=p[3])&&y.getElementsByClassName&&
b.getElementsByClassName)return ba.apply(n,b.getElementsByClassName(e)),n}if(!(!y.qsa||O[a+" "]||w&&w.test(a))){if(1!==R)I=b,g=a;else if("object"!==b.nodeName.toLowerCase()){(h=b.getAttribute("id"))?h=h.replace(ya,"\\$&"):b.setAttribute("id",h=E);q=qa(a);for(f=q.length;f--;)q[f]="[id='"+h+"'] "+D(q[f]);g=q.join(",");I=ua.test(a)&&r(b.parentNode)||b}if(g)try{return ba.apply(n,I.querySelectorAll(g)),n}catch(k){}finally{h===E&&b.removeAttribute("id")}}}return Aa(a.replace(ha,"$1"),b,n,c)}catch(k){return[]}}
function c(){function a(n,c){b.push(n+" ")>t.cacheLength&&delete a[b.shift()];return a[n+" "]=c}var b=[];return a}function f(a){a[E]=!0;return a}function e(a){var b=A.createElement("div");try{return!!a(b)}catch(n){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function k(a,b){for(var n=a.split("|"),c=a.length;c--;)t.attrHandle[n[c]]=b}function m(a,b){var n=b&&a,c=n&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(c)return c;if(n)for(;n=n.nextSibling;)if(n===
b)return-1;return a?1:-1}function v(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var n=b.nodeName.toLowerCase();return("input"===n||"button"===n)&&b.type===a}}function d(a){return f(function(b){b=+b;return f(function(n,c){for(var e,f=a([],n.length,b),d=f.length;d--;)n[e=f[d]]&&(n[e]=!(c[e]=n[e]))})})}function r(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function N(){}function D(a){for(var b=0,n=a.length,c="";b<n;b++)c+=
a[b].value;return c}function K(a,b,n){var c=b.dir,e=n&&"parentNode"===c,f=ia++;return b.first?function(b,h,p){for(;b=b[c];)if(1===b.nodeType||e)return a(b,h,p)}:function(b,h,p){var q,g,I=[P,f];if(p)for(;b=b[c];){if((1===b.nodeType||e)&&a(b,h,p))return!0}else for(;b=b[c];)if(1===b.nodeType||e){g=b[E]||(b[E]={});g=g[b.uniqueID]||(g[b.uniqueID]={});if((q=g[c])&&q[0]===P&&q[1]===f)return I[2]=q[2];g[c]=I;if(I[2]=a(b,h,p))return!0}}}function B(a){return 1<a.length?function(b,n,c){for(var e=a.length;e--;)if(!a[e](b,
n,c))return!1;return!0}:a[0]}function G(a,b,n,c,e){for(var f,d=[],h=0,p=a.length,q=null!=b;h<p;h++)if(f=a[h])if(!n||n(f,c,e))d.push(f),q&&b.push(h);return d}function H(a,c,n,e,d,k){e&&!e[E]&&(e=H(e));d&&!d[E]&&(d=H(d,k));return f(function(f,h,p,q){var g,I,R=[],k=[],u=h.length,l;if(!(l=f)){l=c||"*";for(var m=p.nodeType?[p]:p,r=[],V=0,t=m.length;V<t;V++)b(l,m[V],r);l=r}l=!a||!f&&c?l:G(l,R,a,p,q);m=n?d||(f?a:u||e)?[]:h:l;n&&n(l,m,p,q);if(e)for(g=G(m,k),e(g,[],p,q),p=g.length;p--;)if(I=g[p])m[k[p]]=!(l[k[p]]=
I);if(f){if(d||a){if(d){g=[];for(p=m.length;p--;)(I=m[p])&&g.push(l[p]=I);d(null,m=[],g,q)}for(p=m.length;p--;)(I=m[p])&&-1<(g=d?J(f,I):R[p])&&(f[g]=!(h[g]=I))}}else m=G(m===h?m.splice(u,m.length):m),d?d(null,h,m,q):ba.apply(h,m)})}function x(a){var b,n,c,e=a.length,f=t.relative[a[0].type];n=f||t.relative[" "];for(var d=f?1:0,h=K(function(h){return h===b},n,!0),p=K(function(h){return-1<J(b,h)},n,!0),q=[function(q,a,Z){q=!f&&(Z||a!==ra)||((b=a).nodeType?h(q,a,Z):p(q,a,Z));b=null;return q}];d<e;d++)if(n=
t.relative[a[d].type])q=[K(B(q),n)];else{n=t.filter[a[d].type].apply(null,a[d].matches);if(n[E]){for(c=++d;c<e&&!t.relative[a[c].type];c++);return H(1<d&&B(q),1<d&&D(a.slice(0,d-1).concat({value:" "===a[d-2].type?"*":""})).replace(ha,"$1"),n,d<c&&x(a.slice(d,c)),c<e&&x(a=a.slice(c)),c<e&&D(a))}q.push(n)}return B(q)}function z(a,c){var n=0<c.length,e=0<a.length,d=function(d,f,h,p,q){var g,I,R,k=0,l="0",m=d&&[],ca=[],r=ra,V=d||e&&t.find.TAG("*",q),v=P+=null==r?1:Math.random()||.1,x=V.length;for(q&&
(ra=f===A||f||q);l!==x&&null!=(g=V[l]);l++){if(e&&g){I=0;f||g.ownerDocument===A||(aa(g),h=!M);for(;R=a[I++];)if(R(g,f||A,h)){p.push(g);break}q&&(P=v)}n&&((g=!R&&g)&&k--,d&&m.push(g))}k+=l;if(n&&l!==k){for(I=0;R=c[I++];)R(m,ca,f,h);if(d){if(0<k)for(;l--;)m[l]||ca[l]||(ca[l]=Fa.call(p));ca=G(ca)}ba.apply(p,ca);q&&!d&&0<ca.length&&1<k+c.length&&b.uniqueSort(p)}q&&(P=v,ra=r);return m};return n?f(d):d}var C,y,t,sa,Ba,qa,ta,Aa,ra,da,W,aa,A,U,M,w,X,ma,ga,E="sizzle"+1*new Date,S=a.document,P=0,ia=0,ea=c(),
va=c(),O=c(),wa=function(a,b){a===b&&(W=!0);return 0},xa={}.hasOwnProperty,fa=[],Fa=fa.pop,Ga=fa.push,ba=fa.push,na=fa.slice,J=function(a,b){for(var n=0,c=a.length;n<c;n++)if(a[n]===b)return n;return-1},Ca=RegExp("[\\x20\\t\\r\\n\\f]+","g"),ha=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),Da=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Ea=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,ja=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),oa=
/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,F=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ka={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,
PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,
needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},Ha=/^(?:input|select|textarea|button)$/i,L=/^h\d$/i,pa=/^[^{]+\{\s*\[native \w/,za=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ua=/[+~]/,ya=/'|\\/g,Q=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),Y=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)},la=function(){aa()};
try{ba.apply(fa=na.call(S.childNodes),S.childNodes),fa[S.childNodes.length].nodeType}catch(Z){ba={apply:fa.length?function(a,b){Ga.apply(a,na.call(b))}:function(a,b){for(var c=a.length,Z=0;a[c++]=b[Z++];);a.length=c-1}}}y=b.support={};Ba=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};aa=b.setDocument=function(a){var b;a=a?a.ownerDocument||a:S;if(a===A||9!==a.nodeType||!a.documentElement)return A;A=a;U=A.documentElement;M=!Ba(A);A.documentMode&&(b=A.defaultView)&&
b.top!==b&&(b.addEventListener?b.addEventListener("unload",la,!1):b.attachEvent&&b.attachEvent("onunload",la));y.attributes=e(function(a){a.className="i";return!a.getAttribute("className")});y.getElementsByTagName=e(function(a){a.appendChild(A.createComment(""));return!a.getElementsByTagName("*").length});y.getElementsByClassName=pa.test(A.getElementsByClassName);y.getById=e(function(a){U.appendChild(a).id=E;return!A.getElementsByName||!A.getElementsByName(E).length});y.getById?(t.find.ID=function(a,
b){if("undefined"!==typeof b.getElementById&&M){var c=b.getElementById(a);return c?[c]:[]}},t.filter.ID=function(a){var b=a.replace(Q,Y);return function(a){return a.getAttribute("id")===b}}):(delete t.find.ID,t.filter.ID=function(a){var b=a.replace(Q,Y);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}});t.find.TAG=y.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a);if(y.qsa)return b.querySelectorAll(a)}:
function(a,b){var c,d=[],e=0,h=b.getElementsByTagName(a);if("*"===a){for(;c=h[e++];)1===c.nodeType&&d.push(c);return d}return h};t.find.CLASS=y.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&M)return b.getElementsByClassName(a)};X=[];w=[];if(y.qsa=pa.test(A.querySelectorAll))e(function(a){U.appendChild(a).innerHTML="<a id='"+E+"'></a><select id='"+E+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&
w.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||w.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll("[id~="+E+"-]").length||w.push("~=");a.querySelectorAll(":checked").length||w.push(":checked");a.querySelectorAll("a#"+E+"+*").length||w.push(".#.+[+~]")}),e(function(a){var b=A.createElement("input");b.setAttribute("type","hidden");
a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&w.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||w.push(":enabled",":disabled");a.querySelectorAll("*,:x");w.push(",.*:")});(y.matchesSelector=pa.test(ma=U.matches||U.webkitMatchesSelector||U.mozMatchesSelector||U.oMatchesSelector||U.msMatchesSelector))&&e(function(a){y.disconnectedMatch=ma.call(a,"div");ma.call(a,"[s!='']:x");X.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});
w=w.length&&new RegExp(w.join("|"));X=X.length&&new RegExp(X.join("|"));ga=(b=pa.test(U.compareDocumentPosition))||pa.test(U.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};wa=b?function(a,b){if(a===b)return W=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;
if(c)return c;c=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):1;return c&1||!y.sortDetached&&b.compareDocumentPosition(a)===c?a===A||a.ownerDocument===S&&ga(S,a)?-1:b===A||b.ownerDocument===S&&ga(S,b)?1:da?J(da,a)-J(da,b):0:c&4?-1:1}:function(a,b){if(a===b)return W=!0,0;var c,d=0;c=a.parentNode;var e=b.parentNode,h=[a],p=[b];if(!c||!e)return a===A?-1:b===A?1:c?-1:e?1:da?J(da,a)-J(da,b):0;if(c===e)return m(a,b);for(c=a;c=c.parentNode;)h.unshift(c);for(c=b;c=c.parentNode;)p.unshift(c);
for(;h[d]===p[d];)d++;return d?m(h[d],p[d]):h[d]===S?-1:p[d]===S?1:0};return A};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==A&&aa(a);c=c.replace(ja,"='$1']");if(!(!y.matchesSelector||!M||O[c+" "]||X&&X.test(c)||w&&w.test(c)))try{var d=ma.call(a,c);if(d||y.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(e){}return 0<b(c,A,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==A&&aa(a);return ga(a,b)};b.attr=
function(a,b){(a.ownerDocument||a)!==A&&aa(a);var c=t.attrHandle[b.toLowerCase()],c=c&&xa.call(t.attrHandle,b.toLowerCase())?c(a,b,!M):void 0;return void 0!==c?c:y.attributes||!M?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;W=!y.detectDuplicates;da=!y.sortStable&&a.slice(0);a.sort(wa);if(W){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],
1)}da=null;return a};sa=b.getText=function(a){var b,c="",d=0;b=a.nodeType;if(!b)for(;b=a[d++];)c+=sa(b);else if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=sa(a)}else if(3===b||4===b)return a.nodeValue;return c};t=b.selectors={cacheLength:50,createPseudo:f,match:ka,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=
a[1].replace(Q,Y);a[3]=(a[3]||a[4]||a[5]||"").replace(Q,Y);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(ka.CHILD.test(a[0]))return null;a[3]?a[2]=a[4]||a[5]||"":c&&oa.test(c)&&(b=qa(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(Q,Y).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ea[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),ea(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,c,d){return function(e){e=b.attr(e,
a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(Ca," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),k="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(h){return!!h.parentNode}:function(p,q,g){var b,c,l,n,m;q=f!==k?"nextSibling":"previousSibling";var T=
p.parentNode,r=h&&p.nodeName.toLowerCase();g=!g&&!h;b=!1;if(T){if(f){for(;q;){for(l=p;l=l[q];)if(h?l.nodeName.toLowerCase()===r:1===l.nodeType)return!1;m=q="only"===a&&!m&&"nextSibling"}return!0}m=[k?T.firstChild:T.lastChild];if(k&&g)for(l=T,c=l[E]||(l[E]={}),c=c[l.uniqueID]||(c[l.uniqueID]={}),b=c[a]||[],b=(n=b[0]===P&&b[1])&&b[2],l=n&&T.childNodes[n];l=++n&&l&&l[q]||(b=n=0)||m.pop();){if(1===l.nodeType&&++b&&l===p){c[a]=[P,n,b];break}}else if(g&&(l=p,c=l[E]||(l[E]={}),c=c[l.uniqueID]||(c[l.uniqueID]=
{}),b=c[a]||[],b=n=b[0]===P&&b[1]),!1===b)for(;(l=++n&&l&&l[q]||(b=n=0)||m.pop())&&((h?l.nodeName.toLowerCase()!==r:1!==l.nodeType)||!++b||(g&&(c=l[E]||(l[E]={}),c=c[l.uniqueID]||(c[l.uniqueID]={}),c[a]=[P,b]),l!==p)););b-=e;return b===d||0===b%d&&0<=b/d}}},PSEUDO:function(a,c){var d,e=t.pseudos[a]||t.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return e[E]?e(c):1<e.length?(d=[a,a,"",c],t.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,b){for(var d,h=e(a,c),p=h.length;p--;)d=
J(a,h[p]),a[d]=!(b[d]=h[p])}):function(a){return e(a,0,d)}):e}},pseudos:{not:f(function(a){var b=[],c=[],d=ta(a.replace(ha,"$1"));return d[E]?f(function(a,b,c,h){h=d(a,null,h,[]);for(var p=a.length;p--;)if(c=h[p])a[p]=!(b[p]=c)}):function(a,e,f){b[0]=a;d(b,null,f,c);b[0]=null;return!c.pop()}}),has:f(function(a){return function(c){return 0<b(a,c).length}}),contains:f(function(a){a=a.replace(Q,Y);return function(b){return-1<(b.textContent||b.innerText||sa(b)).indexOf(a)}}),lang:f(function(a){F.test(a||
"")||b.error("unsupported lang: "+a);a=a.replace(Q,Y).toLowerCase();return function(b){var c;do if(c=M?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===U},focus:function(a){return a===A.activeElement&&(!A.hasFocus||A.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:function(a){return!1===
a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return L.test(a.nodeName)},input:function(a){return Ha.test(a.nodeName)},button:function(a){var b=
a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:d(function(){return[0]}),last:d(function(a,b){return[b-1]}),eq:d(function(a,b,c){return[0>c?c+b:c]}),even:d(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:d(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:d(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);
return a}),gt:d(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};t.pseudos.nth=t.pseudos.eq;for(C in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[C]=v(C);for(C in{submit:!0,reset:!0})t.pseudos[C]=l(C);N.prototype=t.filters=t.pseudos;t.setFilters=new N;qa=b.tokenize=function(a,c){var d,e,f,l,k,h,p;if(k=va[a+" "])return c?0:k.slice(0);k=a;h=[];for(p=t.preFilter;k;){if(!d||(e=Da.exec(k)))e&&(k=k.slice(e[0].length)||k),h.push(f=[]);d=!1;if(e=Ea.exec(k))d=e.shift(),f.push({value:d,
type:e[0].replace(ha," ")}),k=k.slice(d.length);for(l in t.filter)!(e=ka[l].exec(k))||p[l]&&!(e=p[l](e))||(d=e.shift(),f.push({value:d,type:l,matches:e}),k=k.slice(d.length));if(!d)break}return c?k.length:k?b.error(a):va(a,h).slice(0)};ta=b.compile=function(a,b){var c,d=[],e=[],f=O[a+" "];if(!f){b||(b=qa(a));for(c=b.length;c--;)f=x(b[c]),f[E]?d.push(f):e.push(f);f=O(a,z(e,d));f.selector=a}return f};Aa=b.select=function(a,b,c,d){var e,f,l,h,p="function"===typeof a&&a,q=!d&&qa(a=p.selector||a);c=c||
[];if(1===q.length){f=q[0]=q[0].slice(0);if(2<f.length&&"ID"===(l=f[0]).type&&y.getById&&9===b.nodeType&&M&&t.relative[f[1].type]){b=(t.find.ID(l.matches[0].replace(Q,Y),b)||[])[0];if(!b)return c;p&&(b=b.parentNode);a=a.slice(f.shift().value.length)}for(e=ka.needsContext.test(a)?0:f.length;e--;){l=f[e];if(t.relative[h=l.type])break;if(h=t.find[h])if(d=h(l.matches[0].replace(Q,Y),ua.test(f[0].type)&&r(b.parentNode)||b)){f.splice(e,1);a=d.length&&D(f);if(!a)return ba.apply(c,d),c;break}}}(p||ta(a,q))(d,
b,!M,c,!b||ua.test(a)&&r(b.parentNode)||b);return c};y.sortStable=E.split("").sort(wa).join("")===E;y.detectDuplicates=!!W;aa();y.sortDetached=e(function(a){return a.compareDocumentPosition(A.createElement("div"))&1});e(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||k("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});y.attributes&&e(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value",
"");return""===a.firstChild.getAttribute("value")})||k("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});e(function(a){return null==a.getAttribute("disabled")})||k("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});a._da_Sizzle=b})(window);
function diff_match_patch(){this.Diff_Timeout=1;this.Diff_EditCost=4;this.Match_Threshold=.5;this.Match_Distance=1E3;this.Patch_DeleteThreshold=.5;this.Patch_Margin=4;this.Match_MaxBits=32}var DIFF_DELETE=-1,DIFF_INSERT=1,DIFF_EQUAL=0;
diff_match_patch.prototype.diff_main=function(a,b,c,f){if(window._dijstop)return[];"undefined"==typeof f&&(f=0>=this.Diff_Timeout?Number.MAX_VALUE:(new Date).getTime()+1E3*this.Diff_Timeout);if(null==a||null==b)throw Error("Null input. (diff_main)");if(a==b)return a?[[DIFF_EQUAL,a]]:[];"undefined"==typeof c&&(c=!0);var e=c,k=this.diff_commonPrefix(a,b);c=a.substring(0,k);a=a.substring(k);b=b.substring(k);if(window._dijstop)return[];var k=this.diff_commonSuffix(a,b),m=a.substring(a.length-k);a=a.substring(0,
a.length-k);b=b.substring(0,b.length-k);if(window._dijstop)return[];a=this.diff_compute_(a,b,e,f);c&&a.unshift([DIFF_EQUAL,c]);m&&a.push([DIFF_EQUAL,m]);if(window._dijstop)return[];this.diff_cleanupMerge(a);return a};
diff_match_patch.prototype.diff_compute_=function(a,b,c,f){if(!a)return[[DIFF_INSERT,b]];if(!b)return[[DIFF_DELETE,a]];var e=a.length>b.length?a:b,k=a.length>b.length?b:a,m=e.indexOf(k);if(-1!=m)return c=[[DIFF_INSERT,e.substring(0,m)],[DIFF_EQUAL,k],[DIFF_INSERT,e.substring(m+k.length)]],a.length>b.length&&(c[0][0]=c[2][0]=DIFF_DELETE),c;if(1==k.length)return[[DIFF_DELETE,a],[DIFF_INSERT,b]];if(e=this.diff_halfMatch_(a,b)){b=e[1];k=e[3];a=e[4];e=this.diff_main(e[0],e[2],c,f);if(window._dijstop)return[];
c=this.diff_main(b,k,c,f);return window._dijstop?[]:e.concat([[DIFF_EQUAL,a]],c)}return c&&100<a.length&&100<b.length&&!window._dijstop?this.diff_lineMode_(a,b,f):this.diff_bisect_(a,b,f)};
diff_match_patch.prototype.diff_lineMode_=function(a,b,c){var f=this.diff_linesToChars_(a,b);a=f.chars1;b=f.chars2;f=f.lineArray;a=this.diff_main(a,b,!1,c);this.diff_charsToLines_(a,f);this.diff_cleanupSemantic(a);a.push([DIFF_EQUAL,""]);for(var e=f=b=0,k="",m="";b<a.length;){switch(a[b][0]){case DIFF_INSERT:e++;m+=a[b][1];break;case DIFF_DELETE:f++;k+=a[b][1];break;case DIFF_EQUAL:if(1<=f&&1<=e){a.splice(b-f-e,f+e);b=b-f-e;f=this.diff_main(k,m,!1,c);for(e=f.length-1;0<=e;e--)a.splice(b,0,f[e]);b+=
f.length}f=e=0;m=k=""}b++}a.pop();return a};
diff_match_patch.prototype.diff_bisect_=function(a,b,c){for(var f=a.length,e=b.length,k=Math.ceil((f+e)/2),m=2*k,v=Array(m),l=Array(m),d=0;d<m;d++)v[d]=-1,l[d]=-1;v[k+1]=0;l[k+1]=0;for(var d=f-e,r=0!=d%2,N=0,D=0,K=0,B=0,G=0;G<k&&!((new Date).getTime()>c);G++){for(var H=-G+N;H<=G-D;H+=2){var x=k+H,z;z=H==-G||H!=G&&v[x-1]<v[x+1]?v[x+1]:v[x-1]+1;for(var C=z-H;z<f&&C<e&&a.charAt(z)==b.charAt(C);)z++,C++;v[x]=z;if(z>f)D+=2;else if(C>e)N+=2;else if(r&&(x=k+d-H,0<=x&&x<m&&-1!=l[x])){var y=f-l[x];if(z>=y)return this.diff_bisectSplit_(a,
b,z,C,c)}}for(H=-G+K;H<=G-B;H+=2){x=k+H;y=H==-G||H!=G&&l[x-1]<l[x+1]?l[x+1]:l[x-1]+1;for(z=y-H;y<f&&z<e&&a.charAt(f-y-1)==b.charAt(e-z-1);)y++,z++;l[x]=y;if(y>f)B+=2;else if(z>e)K+=2;else if(!r&&(x=k+d-H,0<=x&&x<m&&-1!=v[x]&&(z=v[x],C=k+z-x,y=f-y,z>=y)))return this.diff_bisectSplit_(a,b,z,C,c)}}return[[DIFF_DELETE,a],[DIFF_INSERT,b]]};
diff_match_patch.prototype.diff_bisectSplit_=function(a,b,c,f,e){var k=a.substring(0,c),m=b.substring(0,f);a=a.substring(c);b=b.substring(f);k=this.diff_main(k,m,!1,e);e=this.diff_main(a,b,!1,e);return k.concat(e)};
diff_match_patch.prototype.diff_linesToChars_=function(a,b){function c(a){for(var b="",c=0,k=-1,m=f.length;k<a.length-1;){k=a.indexOf("\n",c);-1==k&&(k=a.length-1);var D=a.substring(c,k+1),c=k+1;(e.hasOwnProperty?e.hasOwnProperty(D):void 0!==e[D])?b+=String.fromCharCode(e[D]):(b+=String.fromCharCode(m),e[D]=m,f[m++]=D)}return b}var f=[],e={};f[0]="";var k=c(a),m=c(b);return{chars1:k,chars2:m,lineArray:f}};
diff_match_patch.prototype.diff_charsToLines_=function(a,b){for(var c=0;c<a.length;c++){for(var f=a[c][1],e=[],k=0;k<f.length;k++)e[k]=b[f.charCodeAt(k)];a[c][1]=e.join("")}};diff_match_patch.prototype.diff_commonPrefix=function(a,b){if(!a||!b||a.charAt(0)!=b.charAt(0))return 0;for(var c=0,f=Math.min(a.length,b.length),e=f,k=0;c<e;)a.substring(k,e)==b.substring(k,e)?k=c=e:f=e,e=Math.floor((f-c)/2+c);return e};
diff_match_patch.prototype.diff_commonSuffix=function(a,b){if(!a||!b||a.charAt(a.length-1)!=b.charAt(b.length-1))return 0;for(var c=0,f=Math.min(a.length,b.length),e=f,k=0;c<e;)a.substring(a.length-e,a.length-k)==b.substring(b.length-e,b.length-k)?k=c=e:f=e,e=Math.floor((f-c)/2+c);return e};
diff_match_patch.prototype.diff_commonOverlap_=function(a,b){var c=a.length,f=b.length;if(0==c||0==f)return 0;c>f?a=a.substring(c-f):c<f&&(b=b.substring(0,c));c=Math.min(c,f);if(a==b)return c;for(var f=0,e=1;;){var k=a.substring(c-e),k=b.indexOf(k);if(-1==k)return f;e+=k;if(0==k||a.substring(c-e)==b.substring(0,e))f=e,e++}};
diff_match_patch.prototype.diff_halfMatch_=function(a,b){function c(a,b,c){for(var e=a.substring(c,c+Math.floor(a.length/4)),f=-1,l="",m,v,x,z;-1!=(f=b.indexOf(e,f+1));){var C=k.diff_commonPrefix(a.substring(c),b.substring(f)),y=k.diff_commonSuffix(a.substring(0,c),b.substring(0,f));l.length<y+C&&(l=b.substring(f-y,f)+b.substring(f,f+C),m=a.substring(0,c-y),v=a.substring(c+C),x=b.substring(0,f-y),z=b.substring(f+C))}return 2*l.length>=a.length?[m,v,x,z,l]:null}if(0>=this.Diff_Timeout)return null;
var f=a.length>b.length?a:b,e=a.length>b.length?b:a;if(4>f.length||2*e.length<f.length)return null;var k=this,m=c(f,e,Math.ceil(f.length/4)),f=c(f,e,Math.ceil(f.length/2));if(m||f)m=f?m?m[4].length>f[4].length?m:f:f:m;else return null;var v,l;a.length>b.length?(f=m[0],e=m[1],v=m[2],l=m[3]):(v=m[0],l=m[1],f=m[2],e=m[3]);return[f,e,v,l,m[4]]};
diff_match_patch.prototype.diff_cleanupSemantic=function(a){for(var b=!1,c=[],f=0,e=null,k=0,m=0,v=0,l=0,d=0;k<a.length;)a[k][0]==DIFF_EQUAL?(c[f++]=k,m=l,v=d,d=l=0,e=a[k][1]):(a[k][0]==DIFF_INSERT?l+=a[k][1].length:d+=a[k][1].length,e&&e.length<=Math.max(m,v)&&e.length<=Math.max(l,d)&&(a.splice(c[f-1],0,[DIFF_DELETE,e]),a[c[f-1]+1][0]=DIFF_INSERT,f--,f--,k=0<f?c[f-1]:-1,d=l=v=m=0,e=null,b=!0)),k++;b&&this.diff_cleanupMerge(a);this.diff_cleanupSemanticLossless(a);for(k=1;k<a.length;){if(a[k-1][0]==
DIFF_DELETE&&a[k][0]==DIFF_INSERT){b=a[k-1][1];c=a[k][1];f=this.diff_commonOverlap_(b,c);e=this.diff_commonOverlap_(c,b);if(f>=e){if(f>=b.length/2||f>=c.length/2)a.splice(k,0,[DIFF_EQUAL,c.substring(0,f)]),a[k-1][1]=b.substring(0,b.length-f),a[k+1][1]=c.substring(f),k++}else if(e>=b.length/2||e>=c.length/2)a.splice(k,0,[DIFF_EQUAL,b.substring(0,e)]),a[k-1][0]=DIFF_INSERT,a[k-1][1]=c.substring(0,c.length-e),a[k+1][0]=DIFF_DELETE,a[k+1][1]=b.substring(e),k++;k++}k++}};
diff_match_patch.prototype.diff_cleanupSemanticLossless=function(a){function b(a,b){if(!a||!b)return 6;var c=a.charAt(a.length-1),d=b.charAt(0),e=c.match(diff_match_patch.nonAlphaNumericRegex_),f=d.match(diff_match_patch.nonAlphaNumericRegex_),l=e&&c.match(diff_match_patch.whitespaceRegex_),k=f&&d.match(diff_match_patch.whitespaceRegex_),c=l&&c.match(diff_match_patch.linebreakRegex_),d=k&&d.match(diff_match_patch.linebreakRegex_),m=c&&a.match(diff_match_patch.blanklineEndRegex_),r=d&&b.match(diff_match_patch.blanklineStartRegex_);
return m||r?5:c||d?4:e&&!l&&k?3:l||k?2:e||f?1:0}for(var c=1;c<a.length-1;){if(a[c-1][0]==DIFF_EQUAL&&a[c+1][0]==DIFF_EQUAL){var f=a[c-1][1],e=a[c][1],k=a[c+1][1],m=this.diff_commonSuffix(f,e);if(m)var v=e.substring(e.length-m),f=f.substring(0,f.length-m),e=v+e.substring(0,e.length-m),k=v+k;for(var m=f,v=e,l=k,d=b(f,e)+b(e,k);e.charAt(0)===k.charAt(0);){var f=f+e.charAt(0),e=e.substring(1)+k.charAt(0),k=k.substring(1),r=b(f,e)+b(e,k);r>=d&&(d=r,m=f,v=e,l=k)}a[c-1][1]!=m&&(m?a[c-1][1]=m:(a.splice(c-
1,1),c--),a[c][1]=v,l?a[c+1][1]=l:(a.splice(c+1,1),c--))}c++}};diff_match_patch.nonAlphaNumericRegex_=/[^a-zA-Z0-9]/;diff_match_patch.whitespaceRegex_=/\s/;diff_match_patch.linebreakRegex_=/[\r\n]/;diff_match_patch.blanklineEndRegex_=/\n\r?\n$/;diff_match_patch.blanklineStartRegex_=/^\r?\n\r?\n/;
diff_match_patch.prototype.diff_cleanupEfficiency=function(a){for(var b=!1,c=[],f=0,e=null,k=0,m=!1,v=!1,l=!1,d=!1;k<a.length&&!window._dijstop;)a[k][0]==DIFF_EQUAL?(a[k][1].length<this.Diff_EditCost&&(l||d)?(c[f++]=k,m=l,v=d,e=a[k][1]):(f=0,e=null),l=d=!1):(a[k][0]==DIFF_DELETE?d=!0:l=!0,e&&(m&&v&&l&&d||e.length<this.Diff_EditCost/2&&3==m+v+l+d)&&(a.splice(c[f-1],0,[DIFF_DELETE,e]),a[c[f-1]+1][0]=DIFF_INSERT,f--,e=null,m&&v?(l=d=!0,f=0):(f--,k=0<f?c[f-1]:-1,l=d=!1),b=!0)),k++;b&&!window._dijstop&&
this.diff_cleanupMerge(a)};
diff_match_patch.prototype.diff_cleanupMerge=function(a){a.push([DIFF_EQUAL,""]);for(var b=0,c=0,f=0,e="",k="",m;b<a.length&&!window._dijstop;)switch(a[b][0]){case DIFF_INSERT:f++;k+=a[b][1];b++;break;case DIFF_DELETE:c++;e+=a[b][1];b++;break;case DIFF_EQUAL:1<c+f?(0!==c&&0!==f&&(m=this.diff_commonPrefix(k,e),0!==m&&(0<b-c-f&&a[b-c-f-1][0]==DIFF_EQUAL?a[b-c-f-1][1]+=k.substring(0,m):(a.splice(0,0,[DIFF_EQUAL,k.substring(0,m)]),b++),k=k.substring(m),e=e.substring(m)),m=this.diff_commonSuffix(k,e),
0!==m&&(a[b][1]=k.substring(k.length-m)+a[b][1],k=k.substring(0,k.length-m),e=e.substring(0,e.length-m))),0===c?a.splice(b-f,c+f,[DIFF_INSERT,k]):0===f?a.splice(b-c,c+f,[DIFF_DELETE,e]):a.splice(b-c-f,c+f,[DIFF_DELETE,e],[DIFF_INSERT,k]),b=b-c-f+(c?1:0)+(f?1:0)+1):0!==b&&a[b-1][0]==DIFF_EQUAL?(a[b-1][1]+=a[b][1],a.splice(b,1)):b++,c=f=0,k=e=""}""===a[a.length-1][1]&&a.pop();c=!1;for(b=1;b<a.length-1&&!window._dijstop;)a[b-1][0]==DIFF_EQUAL&&a[b+1][0]==DIFF_EQUAL&&(a[b][1].substring(a[b][1].length-
a[b-1][1].length)==a[b-1][1]?(a[b][1]=a[b-1][1]+a[b][1].substring(0,a[b][1].length-a[b-1][1].length),a[b+1][1]=a[b-1][1]+a[b+1][1],a.splice(b-1,1),c=!0):a[b][1].substring(0,a[b+1][1].length)==a[b+1][1]&&(a[b-1][1]+=a[b+1][1],a[b][1]=a[b][1].substring(a[b+1][1].length)+a[b+1][1],a.splice(b+1,1),c=!0)),b++;c&&!window._dijstop&&this.diff_cleanupMerge(a)};diff_match_patch.prototype.diff_text1=function(a){for(var b=[],c=0;c<a.length&&(a[c][0]!==DIFF_INSERT&&(b[c]=a[c][1]),!window._dijstop);c++);return b.join("")};
diff_match_patch.prototype.match_main=function(a,b,c){if(null==a||null==b||null==c)throw Error("Null input. (match_main)");c=Math.max(0,Math.min(c,a.length));return a==b?0:a.length?a.substring(c,c+b.length)==b?c:this.match_bitap_(a,b,c):-1};
diff_match_patch.prototype.match_bitap_=function(a,b,c){function f(a,d){var e=a/b.length,f=Math.abs(c-d);return k.Match_Distance?e+f/k.Match_Distance:f?1:e}if(b.length>this.Match_MaxBits)throw Error("Pattern too long for this browser.");var e=this.match_alphabet_(b),k=this,m=this.Match_Threshold,v=a.indexOf(b,c);-1!=v&&(m=Math.min(f(0,v),m),v=a.lastIndexOf(b,c+b.length),-1!=v&&(m=Math.min(f(0,v),m)));for(var l=1<<b.length-1,v=-1,d,r,N=b.length+a.length,D,K=0;K<b.length;K++){d=0;for(r=N;d<r;)f(K,c+
r)<=m?d=r:N=r,r=Math.floor((N-d)/2+d);N=r;d=Math.max(1,c-r+1);var B=Math.min(c+r,a.length)+b.length;r=Array(B+2);for(r[B+1]=(1<<K)-1;B>=d;B--){var G=e[a.charAt(B-1)];r[B]=0===K?(r[B+1]<<1|1)&G:(r[B+1]<<1|1)&G|(D[B+1]|D[B])<<1|1|D[B+1];if(r[B]&l&&(G=f(K,B-1),G<=m))if(m=G,v=B-1,v>c)d=Math.max(1,2*c-v);else break}if(f(K+1,c)>m)break;D=r}return v};
diff_match_patch.prototype.match_alphabet_=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=0;for(c=0;c<a.length;c++)b[a.charAt(c)]|=1<<a.length-c-1;return b};
diff_match_patch.prototype.patch_addContext_=function(a,b){if(0!=b.length){for(var c=b.substring(a.start2,a.start2+a.length1),f=0;b.indexOf(c)!=b.lastIndexOf(c)&&c.length<this.Match_MaxBits-this.Patch_Margin-this.Patch_Margin;)f+=this.Patch_Margin,c=b.substring(a.start2-f,a.start2+a.length1+f);f+=this.Patch_Margin;(c=b.substring(a.start2-f,a.start2))&&a.diffs.unshift([DIFF_EQUAL,c]);(f=b.substring(a.start2+a.length1,a.start2+a.length1+f))&&a.diffs.push([DIFF_EQUAL,f]);a.start1-=c.length;a.start2-=
c.length;a.length1+=c.length+f.length;a.length2+=c.length+f.length}};
diff_match_patch.prototype.patch_make=function(a,b,c){var f;if(a&&"object"==typeof a&&"undefined"==typeof b&&"undefined"==typeof c){if(f=this.diff_text1(a),window._dijstop)return[]}else throw Error("Unknown call format to patch_make.");if(0===a.length)return[];b=[];c=new diff_match_patch.patch_obj;for(var e=0,k=0,m=0,v=f,l=0;l<a.length;l++){if(window._dijstop)return[];var d=a[l][0],r=a[l][1];e||d===DIFF_EQUAL||(c.start1=k,c.start2=m);switch(d){case DIFF_INSERT:c.diffs[e++]=a[l];c.length2+=r.length;
f=f.substring(0,m)+r+f.substring(m);break;case DIFF_DELETE:c.length1+=r.length;c.diffs[e++]=a[l];f=f.substring(0,m)+f.substring(m+r.length);break;case DIFF_EQUAL:r.length<=2*this.Patch_Margin&&e&&a.length!=l+1?(c.diffs[e++]=a[l],c.length1+=r.length,c.length2+=r.length):r.length>=2*this.Patch_Margin&&e&&(this.patch_addContext_(c,v),b.push(c),c=new diff_match_patch.patch_obj,e=0,v=f,k=m)}d!==DIFF_INSERT&&(k+=r.length);d!==DIFF_DELETE&&(m+=r.length)}e&&!window._dijstop&&(this.patch_addContext_(c,v),
b.push(c));return b};diff_match_patch.prototype.patch_toText=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b.join("")};diff_match_patch.patch_obj=function(){this.diffs=[];this.start2=this.start1=null;this.length2=this.length1=0};
diff_match_patch.patch_obj.prototype.toString=function(){for(var a=["@@ -"+(0===this.length1?this.start1+",0":1==this.length1?this.start1+1:this.start1+1+","+this.length1)+" +"+(0===this.length2?this.start2+",0":1==this.length2?this.start2+1:this.start2+1+","+this.length2)+" @@\n"],b,c=0;c<this.diffs.length;c++){switch(this.diffs[c][0]){case DIFF_INSERT:b="+";break;case DIFF_DELETE:b="-";break;case DIFF_EQUAL:b=" "}a[c+1]=b+encodeURI(this.diffs[c][1])+"\n"}return a.join("").replace(/%20/g," ")};
this.diff_match_patch=diff_match_patch;this.DIFF_DELETE=DIFF_DELETE;this.DIFF_INSERT=DIFF_INSERT;this.DIFF_EQUAL=DIFF_EQUAL;
(function(a,b,c,f,e,k,m,v,l){function d(h){return"undefined"===typeof h||null===h||""===h}function r(h){return!isNaN(parseFloat(h))&&isFinite(h)}function N(h){for(var a in h)if(h.hasOwnProperty(a))return!1;return!0}function D(h){return"undefined"===typeof h}function K(h){return"string"===typeof h}function B(h){return h===Object(h)}function G(h){return"[object Arguments]"===Object.prototype.toString.call(h)}function H(h){return Array.isArray?Array.isArray(h):"[object Array]"===Object.prototype.toString.call(h)}
function x(h){return"function"===typeof h}function z(h,a){return y(k,h,a)}function C(h,a){return y(m,h,a)}function y(h,a,b){if(la)try{return d(b)?h.removeItem(a):h.setItem(a,b),!0}catch(g){}return!1}function t(){return(new Date).getTime()}function sa(h){return h.replace(u.mask,"*")}function Ba(h,a,b){return a+b.replace(u.mask,"*")}function qa(h,a,b,g){return b+g.replace(u.mask,"*")}function ta(h){var a,b=h.childNodes;"img"===h.tagName.toLowerCase()&&h.getAttribute("_da_remove_src")&&(h.setAttribute("_da_remove_src",
"//app.decibelinsight.com/images/noimg.svg"),h.style.width=h.getAttribute("data-di-width")+"px",h.style.height=h.getAttribute("data-di-height")+"px");for(a in b)b.hasOwnProperty(a)&&(h=b[a],3===h.nodeType?h.nodeValue=h.nodeValue.replace(u.mask,"*"):1===h.nodeType&&ta(h))}function Aa(){var h="",a;l('script[src$="di.js"]').forEach(function(b){a=b.src;u.diTest.test(a)&&(h=b.src)});return h}function ra(h){return h.id&&u.valId.test(h.id)?"#"+h.id:u.body.test(h.tagName)||u.html.test(h.tagName)?h.tagName.toLowerCase():
ra(h.parentNode)+" > "+h.tagName.toLowerCase()+(d(h.href)?"":'[href="'+h.href+'"]')}function da(h,a){var b,g,c,d,e=h.split(","),f=[];b=0;for(g=e.length;b<g;++b)c=e[b].trim().split(" "),d=c.shift(),f.push(W(d,a)+(c.length?" "+c.join(" "):""));return f.join(", ")}function W(h,a,b){var g,c=function(h,a){return a+"/"};D(b)&&(b=!0);h=Ca(h);g=h.charAt(0);'"'===g||"'"===g?h=h.substring(1,h.length-1):g="";Y.href=h;h=Y.href;return"data:"===h.substring(0,5)?2048<h.length&&!b?(a.lb=!0,""):g+h+g:a.hasFlag(1024)&&
"file://"===h.substring(0,7)?g+a.pUrlH+h.replace(u.hUrlFix,"")+g:"http:"===h.substring(0,5)||"https:"===h.substring(0,6)?(x(a.ouC)&&(h=F(a.ouC,a)(h)),h=h.replace(u.urlFix,"").replace(u.protR,c),a.addToPUList(a.pUrl+h),g+a.pUrl+h+g):""}function aa(h){var a,b="",g,c;try{c=h.cssRules||h.rules}catch(e){}g=h.media;g=d(g)||d(g.mediaText)||"all"===g.mediaText||"screen"===g.mediaText?"":u.media.test(g.mediaText)?g.mediaText:!1;if(!1!==g){if(c){for(a in c)c.hasOwnProperty(a)&&(b+=aa(c[a]));g.length&&(b="@media "+
g+" {\n"+b+"}");return b}if(h.cssText)return h.cssText+"\n"}return""}function A(h){l.matches(":not([data-di-id])",l(h)).forEach(function(h){var a;if(a=h.id&&u.valId.test(h.id)||!d(h.href)){a=h;for(var b=!1;!b&&!d(a)&&!u.body.test(a.tagName);)b=!d(a.getAttribute("data-di-id")),a=a.parentNode;a=!b}a&&(a=ra(h),-1<a.indexOf(" ")&&(a="di-id-"+M(a)),h.setAttribute("data-di-id",a))})}function U(h){var p;if(!(p=a._da_crcTable)){var b,g,c=[];for(b=0;256>b;b++){p=b;for(g=0;8>g;g++)p=p&1?3988292384^p>>>1:p>>>
1;c[b]=p}p=a._da_crcTable=c}b=-1;g=0;for(c=h.length;g<c;g++)b=b>>>8^p[(b^h.charCodeAt(g))&255];return(b^-1)>>>0}function M(h){h=""+(d(h)?"":h);return U(h.substr(0,h.length/2)).toString(16)+"-"+U(h.substr(h.length/2)).toString(16)}function w(h,a,b,g,c){d(h)||d(a)||(h.addEventListener?h.addEventListener(a,function(h){b.call(g,h,c)},!1):h.attachEvent&&h.attachEvent("on"+a,function(h){b.call(g,h,c)}))}function X(h){var p=b.documentElement,q={top:0,left:0};if(h&&h.ownerDocument){try{D(h.getBoundingClientRect)||
(q=h.getBoundingClientRect())}catch(g){}return{top:q.top+ia(a)-p.clientTop,left:q.left+ea(a)-p.clientLeft}}}function ma(h,a){return h.currentStyle?h.currentStyle[a]:b.defaultView&&b.defaultView.getComputedStyle?b.defaultView.getComputedStyle(h)[a]:h.style[a]}function ga(){var h,a,b,g=arguments.length;if(0===g)return{};b=arguments[0];for(h=1;h<g;h++)for(a in arguments[h])arguments[h].hasOwnProperty(a)&&(b[a]=arguments[h][a]);return arguments[0]}function E(h,a){var q;q="inner";var g={top:0,bottom:0,
left:0,right:0};if(null!==h&&h===h.window)return"innerWidth"in h||(h=b.documentElement||O(),q="client"),h[q+a];if(9===h.nodeType)return q=h.documentElement,e.max(O()["scroll"+a],q["scroll"+a],O()["offset"+a],q["offset"+a],q["client"+a]);try{D(h.getBoundingClientRect)||(g=h.getBoundingClientRect())}catch(c){}return"width"===a.toLowerCase()?g.right-g.left:g.bottom-g.top}function S(h){return E(h,"Width")}function P(h){return E(h,"Height")}function ia(h){var a=wa(h);return a?a.scrollY||a.pageYOffset||
O().scrollTop||b.documentElement.scrollTop:h.scrollTop}function ea(h){var a=wa(h);return a?a.scrollX||a.pageXOffset||O().scrollLeft||b.documentElement.scrollLeft:h.scrollLeft}function va(){d(ya)&&(ya=l("head")[0]);return ya}function O(){d(Q)&&(Q=l("body")[0]);return Q}function wa(h){return null!==h&&h===h.window?h:9===h.nodeType?h.defaultView||h.parentWindow:!1}function xa(h){var a,q,g,c;a=h.nodeType;if(3===a)q=b.createTextNode(h.nodeValue);else if(8===a)q=b.createComment(h.nodeValue);else if(1===
a&&(q=b.createElement(h.nodeName),!u.script.test(h.nodeName))){for(a=h.firstChild;a;)q.appendChild(xa(a)),a=a.nextSibling;g=h.attributes||[];a=g.length;for(h=0;h<a;h++){c=g[h].name;if("src"===c||"href"===c||"checked"===c)c="_da_remove_"+c;try{q.setAttribute(c,g[h].value)}catch(d){}}}return q}function fa(h,a){h=h.parentNode;if(l.matchesSelector(h,a))return h;if(!u.body.test(h.tagName))return fa(h,a)}function Fa(){var h=[],a,b,g=l(":scrolled");a=0;for(b=g.length;a<b;a++)h.push(oa(g[a])+":"+g[a].scrollTop+
":"+g[a].scrollLeft);return h.join("|")}function Ga(){var h=[];l("input:invalid, select:invalid, textarea:invalid").forEach(function(a){h.push(na(a))});return h.join("|")}function ba(h){var a,b,g=0,c=d(h.parentNode)?[]:h.parentNode.childNodes;a=0;for(b=c.length;a<b;a++){if(c[a]===h)return g;1===c[a].nodeType&&g++}return-1}function na(h){var a,b,c=-1,d=l("input:not([type=hidden]),select,textarea");a=0;for(b=d.length;a<b;a++)if(d[a]===h){c=a;break}return c}function J(h,a,b){var c;if(a)for(c=a.length,
b=b?0>b?e.max(0,c+b):b:0;b<c;b++)if(b in a&&a[b]===h)return b;return-1}function Ca(h){return(h||"").replace(u.trim,"")}function ha(h){h=(h||"").replace(u.lb," ");return h.replace(u.trim,"")}function Da(h){return 10>h?"0"+h:h}function Ea(h){var a,c,g,d,e=b.cookie.split(";");a=0;for(c=e.length;a<c;a++)if(g=e[a].substr(0,e[a].indexOf("=")),d=e[a].substr(e[a].indexOf("=")+1),g=g.replace(u.trim,""),g===h)return unescape(d);return null}function ja(h){return d(h)?"":encodeURIComponent(String(h))}function oa(h){for(var a=
[];!d(h)&&!u.body.test(h.tagName);)a.push(ba(h)),h=h.parentNode;return a.reverse().join("/")}function F(h,a){if(!x(h))return null;var b=T.call(arguments,2);return function(){return h.apply(a||this,b.concat(T.call(arguments)))}}function ka(h,b,c,g){var d,e,f;try{b=b||{},d=new (a.XMLHttpRequest||a.ActiveXObject)("MSXML2.XMLHTTP.3.0"),e=function(a){g&&g(d.status||a.type)},f=function(a){200===d.status?c&&c(d.responseText):e(a)},"onload"in d?(d.onload=f,d.onerror=e,d.onabort=e,d.ontimeout=e):d.onreadystatechange=
function(){4===d.readyState&&f()},d.open(b.data?"POST":"GET",h,!1===b.async?!1:!0),!1!==b.async&&(d.timeout=5E3),d.withCredentials=!0,b.nocache&&(d.setRequestHeader("Cache-Control","no-cache"),d.setRequestHeader("Pragma","no-cache"),Ja&&d.setRequestHeader("If-None-Match","")),d.send(b.data)}catch(l){}}function Ha(){var a,b;try{try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{b.AllowScriptAccess="always"}catch(c){return"6.0.0"}}catch(c){}a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,
".").match(/^\.?(.+)\.?$/)[1];return a.substr(0,50)}catch(c){try{if(f.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return a=(f.plugins["Shockwave Flash 2.0"]||f.plugins["Shockwave Flash"]).description.replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1],a.substr(0,50)}catch(g){}}return"0"}function L(a){var b=typeof a,c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g=function(a){return a.match(u.escape)?a.replace(u.escape,function(a){var h=c[a];if("string"===typeof h)return h;
h=a.charCodeAt();return"\\u00"+e.floor(h/16).toString(16)+(h%16).toString(16)}):a};if("object"!==b||null===a)return"string"===b&&(a='"'+g(a)+'"'),String(a);var d,f,l=[],k=a&&a.constructor===Array;for(d in a)a.hasOwnProperty(d)&&(f=a[d],b=typeof f,"string"===b?f='"'+g(f)+'"':"object"===b&&null!==f&&(f=L(f)),l.push((k?"":'"'+d+'":')+String(f)));return(k?"[":"{")+String(l)+(k?"]":"}")}function pa(h){var b={};try{b=a.JSON&&a.JSON.parse?a.JSON.parse(h):eval("("+h+")")}catch(c){}return b}function za(){-1!==
b.readyState.indexOf("in")?setTimeout(za,9):(a.DecibelInsight=a.DecibelInsight||"decibelInsight",_da_.initiated||u.bot.test(f.userAgent)||(_da_.initiated=!0,new Ia))}var ua="cdn.decibelinsight.net",ya=l("head")[0],Q=l("body")[0],Y=b.createElement("a"),la=!D(k),Z="sendGoal sendIntegrationData updateUserId updateLead updateLeadScore trackPageView indexElements _hm getLeadId getSessionId getPageTime getPageUrl isCollecting formSubmitted indexForms ready isEmpty isNumber isString isEmptyObject isUndefined isObject isArray trim trimnlb isFunction ajax addEvent offset getStyle sendHTTPError extend width height scrollTop scrollLeft closest indexInParent inArray hash getCookie getXPath proxy setFrameRate setCollection setRetention onCollectionChange version sendCustomDimension pauseRecording resumeRecording tabReady getTabId sendApplicationError setSS setLS bindGoalEvents isDomainValid setFavourite".split(" "),
T=Array.prototype.slice,n=/Android/i.test(f.userAgent)&&/Chrome\/[0-9]/i.test(f.userAgent),Ja=/Firefox\/[0-9]/i.test(f.userAgent),ca=/mac/i.test(f.platform),u={body:/^body$/i,boolTrue:/^(true|1)$/i,bot:/(sp[iy]der|[a-z\/_]bot|crawler|slurp|teoma)/i,canvasCss:/(?:^\s*|[\{\},]\s*)([^\{\},]*)\bcanvas\b([^\{,]*)(?=\s*[\{,]+\s*)/gi,cc:/(([>\s({\[|\,;:\"\'])\b((?:3[47]\d{2}([\s-]?)\d{6}\1\d|(?:(?:4\d|5[1-5]|65)\d{2}|6011)([\s-]?)\d{4}\2\d{4}\2)\d{4})\b)/g,comment:/<!\-\-(.|[\r\n])*?\-\->/ig,css:/\.css$/i,
cssUrl:/url\((['"][^'"]+['"]|[^\)]+)\)/g,diTest:/\/i\/([0-9]+\/)?[0-9]+\/di\.js$/i,dWidth:/-device-width[\s]*:/gi,email:/([>\s({\[|\,;:\"\'])([a-z0-9][a-z0-9._\-]{0,30}@([a-z0-9\-]{1,30}\.)+[a-z0-9]{2,5})/gi,escape:/["\\\x00-\x1f\x7f-\x9f]/g,font:/\.(eot|woff|woff2|ttf|svg|otf)$/i,fSel:/(name\=\"|field\-id\=\")/,head:/^head$/i,hPathFix:/^(\/.*\.app\/|\/android_(asset|res)\/)/,html:/^html$/i,hUrlFix:/^file:\/\/(.*\.app\/|\/android_(asset|res)\/)/,idFix:/(:|\.|\[|\]|,|\{|\})/g,invalidInput:/^(datetime\-local|datetime|time|week|month|date|number)$/i,
js:/\.js(\?.*|$)/i,jsO:/(\.js|\/[^\.]+)$/i,jSupB:/(Firefox\/[0-9]|Chrome\/[0-9]|Chromium\/[0-9]|Safari\/[0-9]|AppleWebKit\/[0-9]|Trident\/[6-9]|Edge\/[0-9]|MSIE 9)/i,lb:/[\r\n\s]+/g,mask:/[^\s]/g,media:/all|screen|handheld|min-|max-|resolution|color|aspect-ratio/g,prot:/^(https?:)?\/\//i,protR:/^(https?):\/\//i,pseudoFix:/\:(hover|invalid)/gi,remove:/_da_remove_/ig,regex:/^\/(.*?)\/([gim]*)$/,script:/^script$/i,space:/[\s]{2,}/g,ssn:/\d{3}-\d{2}-\d{4}/gi,textarea:/<textarea(.*? data-di-mask.*?)>([\s\S]*?)<\/textarea>/ig,
trim:/^\s+|\s+$/g,urlFix:/1\.[0-9]\.[0-9]\.[0-9]+\/bmi\//gi,val:/ value=["']([^"]+)["']/,valId:/^[a-z][a-z0-9_\-\:\.]*$/i},Ia=function(){var h=this,b,c=function(){return h.q.push(T.call(arguments))};c.Sizzle=l;l.selectors.pseudos.scrolled=function(a){var h=!1;a!==Q&&(h=0<a.scrollTop||0<a.di_scrollTopOld||0<a.scrollLeft||0<a.di_scrollLeftOld,a.di_scrollTopOld!==a.scrollTop&&(a.di_scrollTopOld=a.scrollTop),a.di_scrollLeftOld!==a.scrollLeft&&(a.di_scrollLeftOld=a.scrollLeft));return h};l.selectors.pseudos.visible=
function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects&&a.getClientRects().length)&&"hidden"!==ma(a,"visibility")&&0!==+ma(a,"opacity")};this.getInitAjaxBuf();h.q=a[a.DecibelInsight]&&a[a.DecibelInsight].q?a[a.DecibelInsight].q:[];a[a.DecibelInsight]=c;for(b=0;b<Z.length;++b)c[Z[b]]=function(a){return function(){return h.q.push([a].concat(T.call(arguments)))}}(Z[b]);x(_da_.preInit)&&_da_.preInit();if(this._init(_da_))for(_da_.err=_da_.err||[],_da_.err.push=function(a){a=G(a)?T.call(a):
[a];h.sendError.apply(h,a)},a.onerror=function(){_da_.err.push(arguments);_da_.oldErr&&_da_.oldErr.apply(a,T.call(arguments))},h.q.push=function(a){return h.processQueue(a)},b=0;b<h.q.length;++b)h.processQueue(T.call(h.q[b]))};Ia.prototype={_da_:null,init:!1,pC:0,dC:0,aTry:3,aBuf:{},aBufI:null,d:[],q:[],tId:0,tQ:[],tD:!1,tC:!1,qs:function(){var a,b,q,g=c.search.substr(1),d={};if(""===g)return d;g=g.split("&");a=0;for(b=g.length;a<b;++a)q=g[a].split("="),2===q.length&&(d[q[0]]=decodeURIComponent(q[1]));
return d}(),sId:null,wId:null,aNum:null,leadId:null,userId:null,optOut:!1,iProt:c.protocol,diLoc:"",iUrl:"",eC:0,pB:[],pBPS:0,pBLT:null,j:!1,jSupB:u.jSupB.test(f.userAgent),jRate:5,jIRate:5,jBuf:[],jBPS:0,jCur:{jE:[],fE:{}},jLast:{},jInt:null,jfInt:null,jrRate:1,jrMin:1E3,jrInt:null,ouC:"",canvasList:{},cssList:{},svgList:{},resList:[],puList:[],puListB:[],jCh:!1,jLT:null,jHtml:{},jPHtml:{},lPHtml:{},isHP:!1,pN:1,jC:1,jSel:"",jDMP:null,pUrl:"",pUrlH:"",rUrl:"",lb:!1,tcanvas:!1,lstyle:!1,altClone:b.documentMode&&
9===b.documentMode||f.vendor&&0===f.vendor.indexOf("Apple")&&/Safari\/[0-9]/i.test(f.userAgent),mTag:l("meta"),pTax:null,pRol:null,fVer:null,time:new Date,lInt:t(),lHov:t(),tZ:(new Date).getTimezoneOffset(),initPV:!1,lan:f.userLanguage?f.userLanguage.replace("_","-"):f.language?f.language.replace("_","-"):"en",java:f.javaEnabled(),ref:b.referrer,tUrl:null,pageUrl:null,pTitle:null,pTC:"",pUC:"",aPT:!0,aUQ:null,aUF:null,fPat:null,sResW:screen.width,sResH:screen.height,vpW:null,vpH:null,svT:null,svL:null,
svB:null,isS:!1,sTi:null,sX:0,sY:0,wTi:null,wld:null,dO:0,mX:0,mY:0,clX:0,clY:0,clT:0,tX:null,tY:null,tTi:0,pT:0,cP:!1,cC:!1,pDs:!1,pDe:!1,tXYT:{x:0,y:0,t:0,ti:0},intSel:null,lIT:0,inTo:null,fixEl:null,fixPos:{top:0,left:0},fes:"",pds:"",pdr:"",maskE:!1,maskS:!1,ufs:"",ifs:"",cS:"",fCol:0,foTC:"",foEC:"",fiTC:"",fiEC:"",srC:0,srT:null,lSS:!1,lst:0,lsl:0,scDur:{},hvT:null,hEl:"",hvDur:{},cInt:null,cIntT:400,hasFocus:!0,focusTime:0,perfTries:0,perfList:[],coll:!0,colcq:[],cto:3E4,pto:5E3,hto:3E3,smo:!D(v),
obs:null,f:!1,forms:[],fbind:[],ffbind:[],ficnt:0,fcInt:null,gList:{},pGoal:!1,flags:0,oFlags:0,scFlags:null,lcFlags:null,_init:function(h){var p,q,g=this;this._da_=this._da_||h;if(1===parseInt(this.get({str:"da_optOut"})))return this.optOut=!0,!1;this.diLoc=Aa();this.smo=this.smo&&!u.boolTrue.test(this.get({_da_:"da_noMutationObserver"}));this.flags=this._da_.da_account_flags;this.oFlags=this._da_.da_account_flags_orig;this.initCollectionStatus();if("?da_optOut"===c.search)return this.optOut=!0,
C("da_optOut",1),q=new Date,q.setFullYear(q.getFullYear(),q.getMonth()+120,q.getDate()),this.hasFlag(8,!0)&&(b.cookie="da_optOut=1; expires="+q.toGMTString()+"; path=/"),alert("You have successfully opted out of Decibel Insight for this domain."),!1;this.sId=this.get({type:"session",str:"_da_da_sessionId",_da_e:"da_sessionId_e"});this.leadId=this.get({type:"lead",str:"_da_da_leadId",_da_e:"da_leadId_e"});this.wId=this.get({_da_:"da_websiteId"});this.aNum=this.get({_da_:"accountNumber"});d(this._da_.da_dnsRecord)||
(ua=this._da_.da_dnsRecord);this.iUrl="//"+ua+"/i/"+this.aNum+"/da/";if(!d(this.sId)&&!d(this.wId)&&!d(this.leadId)){q={userId:"da_userId",fes:"da_fixedElementSelector",pdr:"da_personalDataRegex",pds:"da_personalDataSelector",maskE:"da_maskEmail",maskS:"da_maskSSN",ufs:"da_unmaskFieldSelector",foTC:"formTitleCallback",foEC:"formErrorCallback",fiTC:"fieldTitleCallback",fiEC:"fieldErrorCallback",intSel:"da_interactionSelector",fCol:"da_formCollection",pTax:"da_pageTaxonomy",pRol:"da_pageRole",jRate:"da_frameRate",
jrRate:"da_resourceRate",pTC:"pageTitleCallback",pUC:"pageURLCallback",ifs:"da_ignoreFieldSelector",cS:"da_canvasSelector",aUF:"da_autoFragmentTrack",aUQ:"da_autoQueryTrack",fPat:"da_fragmentPattern",d:"domains",ouC:"optimizeURLCallback",jrMin:"da_minResourceSize"};for(p in q)q.hasOwnProperty(p)&&(this[p]=this.get({_da_:q[p]}));""===this.intSel&&(this.intSel='a,.da_t,input[type="submit"],input[type="button"],button');""===this.ifs&&(this.ifs="[data-di-field-ignore]");r(this.jrRate)||(this.jrRate=
1);r(this.jrMin)||(this.jrMin=1E3);q={pdr:{d:null,o:"g"},fPat:{d:/^#\/.*/,o:""}};for(p in q)if(q.hasOwnProperty(p))if(d(this[p]))this[p]=q[p].d;else{h=this[p].match(u.regex);try{this[p]=h?new RegExp(h[1],h[2]):new RegExp(this[p],q[p].o)}catch(f){this[f]=q[f].d}}this.pageUrl=this.getURL();if(!this.isDomainValid())return B(a.console)&&console.warn&&console.warn("DecibelInsight: "+c.hostname+" is not a valid domain for this account."),!1;this.indexElements();this.hasFlag(2)&&(this.hasFlag(256)||(this.ufs=
""),""!==this.fes&&!d(q=l(this.fes))&&0<q.length&&(this.fixEl=q[0],d(q=X(this.fixEl))||(this.fixPos=q)),this.pTitle=this.getPageTitle(),this.fVer=Ha(),this.vpW=S(a),this.vpH=P(a),this.svT=ia(a),this.svL=ea(a),this.svB=this.vpH+this.svT,this.mX=e.round(this.vpW/2),this.mY=e.round(this.vpH/2),this.startObserver(),(this.aPT=!u.boolTrue.test(this.get({_da_:"da_noAutoPageTrack"})))&&!u.boolTrue.test(Q.getAttribute("di-heatmap"))&&this.tabReady(function(){g.initPV=!0;g.postInfo("page",g.pageData(),{imp:!0,
callback:F(g.runIntScripts,g)});g.initPageTrack()}),this.init=!0)}return!0},initPageTrack:function(){var h,p,c,g,e={};w(a,"scroll",this.scrollEvent,this);w(a,"resize",this.resizeEvent,this);"ontouchstart"in a?(p="touchstart",h="touchend",c="touchmove",g="touchcancel"):f.msPointerEnabled&&!f.pointerEnabled?(p="MSPointerdown",h="MSPointerup",c="MSPointermove",g="MSPointercancel"):f.pointerEnabled&&(p="pointerdown",h="pointerup",c="pointermove",g="pointercancel");p&&(w(b,p,this.pointerDown,this),w(b,
h,this.pointerUp,this),w(b,c,this.pointerMove,this),w(b,g,this.pointerCancel,this));"ontouchstart"in a&&n||(w(b,"mousedown",this.pointerDown,this),w(b,"mouseup",this.pointerUp,this),w(b,"mousemove",this.pointerMove,this));w(b,"contextmenu",this.contextMenu,this);w(b,"keyup",this.getSelection,this);w(a,"beforeunload",this.onExit,this);w(a,"unload",this.onExit,this);w(a,"pagehide",this.onExit,this);w(a,"blur",this.handleBlur,this);w(b,"blur",this.handleBlur,this);w(a,"focus",this.handleFocus,this);
w(b,"focus",this.handleFocus,this);this.srT=new Date;this.hvT=new Date;this.cInt=setInterval(F(this.collIntervalFn,this),this.cIntT);this.j=this.hasFlag(32)&&!u.boolTrue.test(this.get({_da_:"da_noVisitorJourney"}))&&this.jSupB;this.altClone=this.altClone||u.boolTrue.test(this.get({_da_:"altClone"}));this.startJourney();this.j&&(w(b,"keydown",this.keyDown,this),w(b,"keyup",this.keyUp,this),w(b,"onmousewheel"in b?"mousewheel":"onwheel"in b?"wheel":"DOMMouseScroll",this.onWheel,this),"orientation"in
screen&&screen.orientation.type?(w(screen.orientation,"change",this.screenOrientationChanged,this),this.screenOrientationChanged()):"onorientationchange"in a?(w(a,"orientationchange",this.orientationChanged,this),this.orientationChanged()):"matchMedia"in a&&(this.oQuery=a.matchMedia("(orientation:landscape)"),this.oQuery.addListener(this.oQueryObs),this.oQueryObs(this.oQuery)));_da_.err=_da_.err||[];_da_.err.forEach(function(a){a=G(a)?T.call(a):[a];this.sendError.apply(this,a)},this);this.sendPagePerformance();
this.hasFlag(2048)&&B(a.performance)&&x(a.performance.getEntriesByType)&&this.sendResourcePerformance();this.f=this.hasFlag(128)&&!d(this.fCol)&&0<this.fCol;this.startForm();p=["goalId","goalValue","goalCurrency"];for(h=0;h<p.length;h++)e[p[h]]=this.get({_da_:"da_"+p[h]});this.sendGoal(e.goalId,e.goalValue,e.goalCurrency,this.ref);this.updateLead({companyName:this.get({_da_:"da_companyName"})})},runIntScripts:function(){x(this._da_.intScripts)&&!this.intScriptsDone&&(this.intScriptsDone=!0,this._da_.intScripts())},
processQueue:function(h){var b=h.shift();if(this[b]&&-1!==J(b,Z))return this[b].apply(this,h);B(a.console)&&console.warn&&console.warn("DecibelInsight: Method does not exists: "+b)},version:function(){return"3.24.0"},isDomainValid:function(a){var b,q,g=c.hostname.toLowerCase();q=!1;a=a||this.d;if(H(a)&&0!==a.length)for(b=0;b<a.length&&!(q=a[b].toLowerCase(),q="*"===q.charAt(0)?(new RegExp("^"+q.replace(/\./g,"\\.").replace(/^\*/,"[^\\.]+")+"$")).test(g):"www"===q.substr(0,3)?g===q||g===q.substr(4):
g===q||g==="www."+q);++b);else q=!0;return q},ready:function(a){x(a)&&a()},isCollecting:function(){return this.coll&&this.hasFlag(2)},onCollectionChange:function(a){this.colcq.push(a)},setCollection:function(a,b){var c=this.coll,g=!0===a;this.jCur.jE.push("setCollection");g?(this.coll=g,this.setForceColl(1,b),this.init?c||(this.cInt=setInterval(F(this.collIntervalFn,this),this.cIntT),this.startJourney(),this.startForm(),this.startObserver()):(this.time=new Date,this._init()),this.postInfo("apicall",
{api:"setCollection"})):c&&this.init&&(this.sendScroll(),this.endJourney(),this.endForm(),this.clearTimer(["cInt"]),this.stopObserver(),this.postInfo("apicall",{api:"setCollection"}),this.setForceColl(2,b),this.postInfo("flush"),this.coll=g);this.colcq.forEach(function(a){a(g,c)})},setFavourite:function(){this.hasFlag(2)&&(this.jCur.jE.push("setFavourite"),this.postInfo("apicall",{api:"setFavourite"}),this.postInfo("extra",{favourite:1}))},setRetention:function(){this.hasFlag(2)&&(this.jCur.jE.push("setRetention"),
this.postInfo("apicall",{api:"setRetention"}),this.postInfo("retention","",{imp:!0,counter:!1}))},initCollectionStatus:function(){var a;d(this.scFlags)&&(this.scFlags=this._da_.da_sessCookieFlags||0);d(this.lcFlags)&&(this.lcFlags=this._da_.da_leadCookieFlags||0);2===(2&this.lcFlags)?(C("da_forceColl",2),z("da_forceColl",null)):1===(1&this.lcFlags)?(C("da_forceColl",1),z("da_forceColl",null)):2===(2&this.scFlags)?(z("da_forceColl",2),C("da_forceColl",null)):1===(1&this.scFlags)&&(z("da_forceColl",
1),C("da_forceColl",null));a=+this.get({str:"da_forceColl"});2===a?(this.flags=0,this.coll=!1):1===a&&(this.flags=this.oFlags)},setForceColl:function(a,b){var c=this,g=function(){c.scFlags&=-4;c.lcFlags&=-4};this.hasFlag(2,!0)&&(!1===b?(C("da_forceColl",null),z("da_forceColl",a),g(),this.scFlags|=a):(z("da_forceColl",null),C("da_forceColl",a),g(),this.lcFlags|=a),this.sendCookieFlags(),2===a?this.flags=0:1===a&&(this.flags=this.oFlags))},sendCookieFlags:function(){var a=this.diLoc;this.postInfo("cookieflags&val="+
this.scFlags+"|"+this.lcFlags,"",{imp:!0,counter:!1,callback:function(){ka(a,{nocache:!0})}})},sendError:function(a,b,c,g){var e={};this.hasFlag(64)&&5>this.eC&&!d(a)&&K(a)&&(this.eC++,e.error=a,e.errorUrl=d(b)?"":b.split("?")[0],e.line=d(c)||!r(c)?0:c,e.column=d(g)||!r(g)?0:g,this.postInfo("error",e))},hasFlag:function(a,b){return(a&this.flags)===a||b&&(a&this.oFlags)===a},stopObserver:function(){this.smo&&this.obs&&this.obs.disconnect();this.obs=null},startObserver:function(){this.smo&&(this.stopObserver(),
this.obs=new v(F(this.obsFn,this)),this.obs.observe(O(),{attributes:!0,childList:!0,characterData:!0,subtree:!0}))},orientationChanged:function(){var h=this;setTimeout(function(){h.dO=90===e.abs(a.orientation)?0:1},100)},screenOrientationChanged:function(){this.dO=-1<screen.orientation.type.indexOf("landscape")?0:1},oQueryObs:function(a){this.dO=a.matches?0:1},obsFn:function(a){var b,c=a.length,g=!1,d=!1;for(b=0;b<c;b++)"childList"===a[b].type?(a[b].addedNodes.length&&(g=d=!0),a[b].removedNodes.length&&
(g=!0)):"attributes"===a[b].type&&(g=!0);d&&(this.indexElements(),this.formIndex());g&&(this.jCh=!0)},_hm:function(){this.coll=!1;this.stopObserver();this.clearTimer(["cInt","jInt","jrInt","jfInt","fcInt"]);var a=O(),p=b.createElement("script");p.type="text/javascript";p.src=c.protocol+"//app.decibelinsight.com/js/hm.js?_=1475577588194";p.async=!0;a.appendChild(p);a.style.display="block";b.documentElement.style.display="block"},handleBlur:function(){return this.hasFocus=!1},handleFocus:function(){this.hasFocus=
!0;return!1},collIntervalFn:function(){var a,b,c,g;c=this.fixPos;b=this.mX;var d=this.mY;g=t();this.coll&&(r(c.left)&&r(c.top)&&(b=e.round(b-c.left),d=e.round(d-c.top)),this.hasFocus&&g-this.lInt<this.cto&&(this.srC++,c=this.svT,a=this.svB,a=c-c%10+","+(a-a%10),c=g-this.srT.getTime(),20<e.abs(c-this.cIntT)&&(c=this.cIntT),this.scDur[a]=(this.scDur[a]||0)+c,this.focusTime+=c,this.srT.setTime(g)),this.hasFocus&&g-this.lHov<this.hto&&(this.srC++,b=b-b%3+1+","+(d-d%3+1)+(""===this.hEl?"":","+this.hEl),
c=g-this.hvT.getTime(),20<e.abs(c-this.cIntT)&&(c=this.cIntT),this.hvDur[b]=(this.hvDur[b]||0)+c,this.hvT.setTime(g)),100<=this.srC&&this.sendScroll(),this.aPT&&(g=this.getURL(),(g.url!==this.pageUrl.url&&(null===this.tUrl||g.url!==this.tUrl.url)||this.aUQ&&g.query!==this.pageUrl.query&&(null===this.tUrl||g.query!==this.tUrl.query)||this.aUF&&g.hash!==this.pageUrl.hash&&(null===this.tUrl||g.hash!==this.tUrl.hash))&&this.trackPageView()))},sendPagePerformance:function(){var h,b={};B(a.performance)&&
B(a.performance.timing)&&0<a.performance.timing.loadEventStart?(h=a.performance.timing,b.lid=this.leadId,b.conn=h.requestStart-h.navigationStart,b.down=h.responseEnd-h.requestStart,b.rend=h.loadEventStart-h.responseEnd,b.fire=h.domInteractive-h.navigationStart,this.postInfo("perf",b)):150>this.perfTries++&&setTimeout(F(this.sendPagePerformance,this),100)},sendResourcePerformance:function(h){var b,q=[],g,d,f=this.iUrl,l=a.performance.getEntriesByType("resource"),k=l.length;for(h=h||0;h<k;h++){g=l[h];
d=g.name.split("?")[0];b="";var m=d,n=f,r=m.replace(u.prot,"").split("/")[0];u.prot.test(m)&&-1===m.indexOf(n)&&r!==c.host&&-1===J(d,this.perfList)&&("script"===g.initiatorType&&u.jsO.test(d)?b="script":u.font.test(d)?b="font":u.css.test(d)&&(b="css"),-1!==J(b,["script","css","font"])&&(b={name:d,type:b,con:null,ttfb:null,down:null,dur:e.round(g.responseEnd-g.startTime)},g.responseStart&&(b.con=e.round(g.requestStart-g.startTime),b.ttfb=e.round(g.responseStart-g.requestStart),b.down=e.round(g.responseEnd-
g.responseStart)),0<b.dur&&(q.push(b),this.perfList.push(d))))}q.length&&this.postInfo("resperf",{resources:q});setTimeout(F(this.sendResourcePerformance,this,l.length),1E3)},bindGoalEvents:function(a){B(a)&&!N(a)&&(this.gList=a,this.pGoal=!0)},processClick:function(a){var b;if(!u.body.test(a.tagName)&&!u.html.test(a.tagName)){for(b in this.gList)this.gList.hasOwnProperty(b)&&l.matchesSelector(a,this.gList[b])&&this.sendGoal(b);this.processClick(a.parentNode)}},tabReady:function(h){function b(a,h){C(a,
h);m.removeItem(a)}function c(a){var b=[h];a&&(b=g.tQ,g.tQ=[]);g.tD=!0;for(a=0;a<b.length;a++)x(b[a])&&b[a](g.tId)}var g=this,d=0;this.tD?c():la&&a.addEventListener?(d=+k.getItem("di_tab_max"),a.addEventListener("storage",function(a){null!==a.newValue&&("di_tab_get"===a.key?b("di_tab_set",d):"di_tab_set"===a.key&&(d=e.max(d,+a.newValue),z("di_tab_max",d)))}),(this.tId=+k.getItem("di_tab_id"))?c():(this.tQ.push(h),this.tC||(this.tC=!0,b("di_tab_get",Date.now()),setTimeout(function(){d+=1;b("di_tab_set",
d);z("di_tab_max",d);g.tId=d;z("di_tab_id",g.tId);c(!0)},200)))):(this.tId=0,c())},getTabId:function(){return this.tId},getPageTitle:function(){return x(this.pTC)?F(this.pTC,this)():this.get({_da_:"da_pageTitle"})||b.title},getURL:function(){var a,p,q;p=null;x(this.pUC)&&(p=F(this.pUC,this)());if(d(p))a=c;else try{a=b.createElement("a"),a.href=p}catch(g){a=c}p=a.host;q=a.pathname;this.hasFlag(1024)&&(d(p)&&(p="hybrid"),q=q.replace(u.hPathFix,"/"));return{url:a.protocol+"//"+p+q,query:d(a.search)?
"":a.search.substr(1),hash:!d(a.hash)&&this.fPat.test(a.hash)?a.hash.substr(1):""}},getPageUrl:function(){d(this.pageUrl)&&(this.pageUrl=this.getURL());var a=this.pageUrl.url;d(this.pageUrl.query)||(a+="?"+this.pageUrl.query);d(this.pageUrl.hash)||(a+="#"+this.pageUrl.hash);return a},getFormSel:function(a){var b=a.getAttribute("id"),c=a.getAttribute("name"),g=a.getAttribute("data-di-form-id");return d(g)?d(b)?d(c)?"[data-di-form-track]:eq("+J(a,l("[data-di-form-track]"))+")":'[data-di-form-track][name="'+
c+'"]':"#"+b.replace(u.idFix,"\\$1"):'[data-di-form-track][data-di-form-id="'+g+'"]'},getFieldSel:function(a){var b=a.tagName.toLowerCase(),c=a.id,g=a.getAttribute("data-di-field-id");return d(g)?d(c)?b+'[name="'+a.name+'"]':"#"+c.replace(u.idFix,"\\$1"):b+'[data-di-field-id="'+g+'"]'},fieldValType:function(a,b){var c="simple";if("radio"===b&&u.fSel.test(a))c="group";else if("checkbox"===b||"radio"===b)c="check";return c},getFieldval:function(a){var b="",c=a.di_entry;c&&("group"===c.valueType?(a=
l(c.sel+":checked",c.form),b=a.length?a[0].value:""):b="check"===c.valueType?a.checked?1:"":a.value);return b},getFormError:function(a){return x(this.foEC)?F(this.foEC,this)(a):!1},getFieldError:function(a){return x(this.fiEC)?F(this.fiEC,this)(a):!1},getFormTitle:function(a){return x(this.foTC)?F(this.foTC,this)(a):""},getFieldTitle:function(a){return x(this.fiTC)?F(this.fiTC,this)(a):""},scanForm:function(){var a=this,b=!1,c,g,e;if(!this.coll)return!1;this.addFormTracker();l("[data-di-form-track]").forEach(function(f){e=
a.getFormSel(f);if(!d(e))if(g=a.forms[e],d(g)){if(g={el:f,sel:e,title:ha(a.getFormTitle(f)),hasTracker:2!==a.fCol&&f.di_formDyn?0:1,submitted:0,error:a.getFormError(f)?1:0,fields:[]},c=a.scanFields(g))a.forms[e]=g,b=!0}else c=a.scanFields(g),b=b||c});this.addFormEvent();return b},scanFields:function(a){var b=this,c=!1,g,e,f,k,m;l.matches(":not("+b.ifs+")",l.matches(":not([type=hidden],[type=submit],[type=reset],[type=image],[type=button]),[data-di-field-include]",l("input,textarea,select",a.el))).forEach(function(l){if(l.id||
l.name||l.getAttribute("data-di-field-id"))g=b.getFieldSel(l),e=a.fields[g],d(e)?(f=b.getFieldError(l),k=l.type.toLowerCase(),e={el:l,form:a.el,sel:g,type:k,title:ha(b.getFieldTitle(l)).substring(0,127),name:l.name||"",diid:l.getAttribute("data-di-field-id")||"",event:null,focustime:0,timespent:0,delay:0,interactions:0,completed:0,changed:0,comValue:"",error:f?1:0,errorStr:f&&K(f)?f:"",valueType:b.fieldValType(g,k)},l.di_entry=e,m=b.getFieldval(l),l.di_entry.origValue=m,l.di_entry.curValue=m,a.fields[g]=
e,c=!0):l.di_entry=e});return c},addFormEvent:function(){var a=this,b,c,g,d;for(b in this.forms)if(a.forms.hasOwnProperty(b))for(d in g=a.forms[b],c=l(b),c.length&&c[0]!==g.el&&(g.el=c[0]),0>J(g.el,a.fbind)&&(w(g.el,"submit",function(b){a.formSubmitted(a.getFormSel(b.target||b.srcElement))},this),this.fbind.push(g.el)),g.fields)g.fields.hasOwnProperty(d)&&l(d,g.el).forEach(function(b){0>J(b,a.ffbind)&&(w(b,"focus",a.fieldEventHandler,a),w(b,"keypress",a.fieldEventHandler,a),w(b,"blur",a.fieldEventHandler,
a),l.matchesSelector(b,"[type=submit],[type=reset],[type=image],[type=button]")?w(b,"click",a.fieldEventHandler,a):w(b,"change",a.fieldEventHandler,a),a.ffbind.push(b))})},fieldEventHandler:function(a){var b=a.target||a.srcElement,c=t(),g=b.di_entry,e=this.getFieldval(b),f=function(){g.changed=g.changed||g.completed&&e!==g.comValue?1:0;g.completed=d(e)?0:1;g.comValue=g.completed?g.curValue:""};this.lInt=c;if("focus"===a.type)g.focustime=c,g.event="focus";else if("keypress"===a.type&&"keypress"!==
g.event)g.event="keypress",g.interactions+=1,g.delay+=g.focustime?c-g.focustime:0;else if("change"===a.type){if(e!==g.curValue){g.event="change";g.curValue=e;if(-1!==J(g.type,["select-one","select-multiple","checkbox","radio"])||0===g.interactions)g.interactions+=1;g.changeTimeout=setTimeout(function(){g.focustime||(g.timespent+=1E3);f()},100)}}else"blur"===a.type?(g.event="blur",clearTimeout(g.changeTimeout),g.changeTimeout=null,g.timespent+=g.focustime?c-g.focustime:0,f(),g.focustime=0,this.sendForm({data:!0})):
"click"===a.type&&(g.event="click",g.timespent+=1E3,g.interactions+=1,g.completed=1,this.sendForm({data:!0}))},sendForm:function(a){if(this.coll&&!N(this.forms)){var b,c,g,d,e,f,l,k={},m=[],n={data:!1,send:!1},V=["delay","timespent","interactions","error"],r={sel:"s",type:"t",name:"na",diid:"di",title:"ti"};ga(n,a);n.data&&(r={sel:"s",type:"t",delay:"de",timespent:"ti",interactions:"in",completed:"co",changed:"ch",error:"er",errorStr:"erStr"});n.send?this.ficnt=0:(this.ficnt++,10<=this.ficnt&&(this.ficnt=
0,n.send=!0));if(n.send){for(g in this.forms)if(this.forms.hasOwnProperty(g)){l=0;a=this.forms[g];e=[];for(d in a.fields)if(a.fields.hasOwnProperty(d)){f=a.fields[d];c={};for(b in r)r.hasOwnProperty(b)&&(c[r[b]]=f[b]);e.push(c);l+=f.timespent;0===l&&0<f.interactions&&(l+=1E3);if(n.data){for(b=0;b<V.length;b++)f[V[b]]=0;f.errorStr=""}}c=a.sel.replace("[data-di-form-track]","");if(128>=c.length)if(e={s:c,n:a.title,e:e,er:a.error},n.data){if(e.ti=l,e.su=a.submitted,l||e.su)a.submitted=0,a.error=0,m.push(e)}else e.cs=
x(this.foEC)?0:1,e.ht=a.hasTracker,a.submitted=0,a.error=0,m.push(e)}k[n.data?"view":"meta"]=m;m.length&&this.postInfo("form",k,{onExit:n.onExit})}}},formIndex:function(){var a=this;this.f&&(this.scanForm()&&this.sendForm({send:!0}),null===this.fcInt&&(this.fcInt=setInterval(function(){a.ffbind.forEach(function(c){c.di_entry&&c!==b.activeElement&&a.getFieldval(c)!==c.di_entry.curValue&&a.fieldEventHandler({type:"change",target:c})})},100)))},indexForms:function(){this.formIndex()},startForm:function(){this.f&&
this.formIndex()},endForm:function(a){this.f&&(this.sendForm({data:!0,send:!0,onExit:a}),this.forms=[],this.ficnt=0,this.clearTimer(["fcInt"]))},addFormTracker:function(){1===this.fCol&&l("form:not([data-di-form-track])").forEach(function(a){a.setAttribute("data-di-form-track","");a.di_formDyn=1})},formSubmitted:function(a){var b=this,c,g,e,f,k,m,n=function(){d(c)||function(){var a=0,h=function(){b.addFormTracker();f=b.forms[b.getFormSel(c)];d(f)&&(e=l(g),e.length&&(f=b.forms[b.getFormSel(e[0])]));
if(d(f))10>++a&&setTimeout(h,200);else{for(k in f.fields)f.fields.hasOwnProperty(k)&&(m=b.getFieldError(f.fields[k].el),f.fields[k].error=m?1:0,f.fields[k].errorStr=m&&K(m)?m:"",f.error=f.error||f.fields[k].error);f.error=f.error||(b.getFormError(c)?1:0);f.submitted=f.error?0:1;b.sendForm({data:!0,send:!0})}};h()}()};this.f&&this.coll&&(d(a)&&(a="[data-di-form-track]"),!d(a.nodeType)&&l.matchesSelector(a,"[data-di-form-track]")?(c=a,g=this.getFormSel(c),n()):K(a)&&function(){var d=0,f=function(){b.addFormTracker();
e=l(a);e.length?(c=e[0],g=b.getFormSel(c),n()):10>++d&&setTimeout(f,200)};f()}())},onWheel:function(b){b=b||a.event;if(this.j&&this.coll){var c=this,d=1===e.max(-1,e.min(1,b.wheelDelta||-b.deltaY||-b.detail))?"wu":"wd";this.wld!==d&&null!==this.wld&&(this.jCur.tE=this.wld);clearTimeout(this.wTi);this.wTi=setTimeout(function(){c.jCur.tE=d;c.wld=null},250);this.wld=d}},checkformValue:function(){var a=this,b,c;l.matches(":not([type=submit],[type=reset],[type=image],[type=file],[type=button],[type=hidden])",
l("input, select, textarea")).forEach(function(g){D(g.di_fieldVal)&&(g.di_fieldVal="");c=(g.type||"").toLowerCase();b="radio"===c||"checkbox"===c?g.checked?"checked":"":g.value;g.di_fieldVal!==b&&(g.di_fieldVal=b,a.valueChanged(g))})},valueChanged:function(a){if(this.j&&this.coll){var b,c=a.tagName.toLowerCase(),g=(a.type||"").toLowerCase();this.lInt=t();if("select"===c)this.jCur.fE["S:I"+na(a)]=a.selectedIndex;else if("radio"===g)this.jCur.fE["R:I"+na(a)]=1;else if("checkbox"===g)this.jCur.fE["C:I"+
na(a)]=a.checked?1:0;else if("input"===c||"textarea"===c)b=a.value.toString(),l.matchesSelector(a,this.ufs)&&"password"!==g||(b="__*"+b.length),this.jCur.fE["I:I"+na(a)]="textarea"===c?b.substr(0,50):b}},keyDown:function(b){b=b||a.event;this.j&&this.coll&&-1!==J(b.keyCode,[65,67,70,80,83,86,88,90])&&!b.shiftKey&&!b.altKey&&(!ca&&b.ctrlKey||ca&&b.metaKey)&&(this.jCur.kE="c"+b.keyCode,this.lInt=t())},keyUp:function(b){b=b||a.event;this.j&&this.coll&&-1!==J(b.keyCode,[8,9,13,33,34,35,36,37,38,39,40,
116])&&(this.jCur.kE=b.keyCode,this.lInt=t())},setFrameRate:function(b,c){d(b)||0>b||10<b||!this.j||(a._dijstop=!0,this.clearTimer(["jInt","jrInt","jfInt"]),this.jRate=b,c||(this.jIRate=b,this.jCur.jE.push("setFrameRate"),this.postInfo("apicall",{api:"setFrameRate"})),0<this.jRate&&(a._dijstop=!1,this.loadResList(),this.scanResource(),this.jInt=setInterval(F(this.buildJourney,this),1E3/this.jRate),this.jrInt=setInterval(F(this.scanResource,this),1E3/this.jrRate),this.jfInt=setInterval(F(this.checkformValue,
this),100)))},pauseRecording:function(a){d(this.jInt)||(this.jCur.jE.push("pauseRecording"),this.postInfo("apicall",{api:"pauseRecording"}),this.setFrameRate(0,!0),!d(a)&&0<a&&setTimeout(F(this.resumeRecording,this,!0),a))},resumeRecording:function(a){d(this.jInt)&&(a||(this.jCur.jE.push("resumeRecording"),this.postInfo("apicall",{api:"resumeRecording"})),this.setFrameRate(this.jIRate,!0))},changeRate:function(a){var b,c;0!==a&&(b=[0,.25,.5,1],-1===J(this.jIRate,b)&&b.push(this.jIRate),c=J(this.jRate,
b),1===a&&c<b.length?this.setFrameRate(b[c+1],!0):-1===a&&0<c&&this.setFrameRate(b[c-1],!0))},buildJourney:function(h){if(this.coll){var c=this,d,g,f,k,m={};f=0;var n=!1,r,u=t(),v,V=0,w,x,y=function(a,b,h){return D(a[b])||a[b]!==h};this.jC++;if(!(h||this.isHP||this.smo&&!this.jCh||!this.smo&&0!==this.jC%3)&&u-this.lInt<this.pto&&!a._dijstop){this.isHP=!0;v=t();m=this.getHtml();k={};r=["htmlAttr","headAttr","bodyAttr","head","body"];for(d=0;d<r.length;++d)g=r[d],-1!==g.indexOf("Attr")?L(this.jHtml[g])===
L(m[g])||a._dijstop||(k[g]=L(m[g]),this.jHtml[g]=m[g]):this.jHtml[g]===m[g]||a._dijstop||(this.prepareHtml(g),w=this.jDMP.diff_main(this.lPHtml[g],this.jPHtml[g],!0),this.jDMP.diff_cleanupEfficiency(w),w=this.jDMP.patch_make(w),w.length&&!a._dijstop&&(k[g]=this.jDMP.patch_toText(w),f=k[g].length,this.jBPS+=f,1E4<this.jBPS&&(n=!0),f>.8*this.jPHtml[g].length&&(delete k[g],k[g+"Inner"]=this.jPHtml[g],this.jBPS=this.jBPS-f+this.jPHtml[g].lengthh,n=!0),f=1,this.lPHtml[g]=this.jPHtml[g]),this.jHtml[g]=
m[g]);N(k)||a._dijstop||(this.jCur.patch=k,this.jCh=!1,d=t(),500<d-v?V=-1:500>=d-v&&this.jRate<this.jIRate&&(V=1));setTimeout(function(){c.isHP=!1},500/this.jRate)}try{x=oa(l(":hover").pop())}catch(z){x=""}r=[["mX",this.mX],["mY",this.mY],["dO",this.dO||0],["sT",e.round(this.svT)],["sL",e.round(this.svL)],["vW",this.vpW],["vH",this.vpH],["aE",oa(b.activeElement)],["hE",x],["iE",Ga()],["sE",Fa()],["f",this.hasFocus?1:0],["meta",this.getPatchMeta()]];for(d=0;d<r.length;++d)g=r[d],y(this.jLast,g[0],
g[1])&&(this.jCur[g[0]]=g[1],f=1);r="cX s tE jE fE kE".split(" ");for(d=0;d<r.length;++d)if(g=this.jCur[r[d]],!(D(g)||B(g)&&N(g))){f=1;break}f&&(this.jCur.pN=this.pN++,this.jCur.t=u-this.time.getTime(),g=this.jCur,this.jCur={jE:[],fE:{}},N(g.fE)?delete g.fE:g.fE=L(g.fE),0===g.jE.length?delete g.jE:g.jE=L(g.jE),this.jBuf.push(g),ga(this.jLast,g));if(10<this.jBuf.length||u-this.jLT>this.pto||n)this.jBuf.length&&(g=this.getParamForReplay(),g.content=L(this.jBuf),this.postInfo("patch",g,{onExit:h,patchSize:this.jBPS})),
this.jBuf=[],this.jBPS=0,this.jLT=u;this.changeRate(V)}},getPatchMeta:function(){return L({pH:P(b)})},getParamForReplay:function(){var a={},b,c=["lb","tcanvas","lstyle"];for(b=0;b<c.length;++b)this[c[b]]&&(a[c[b]]=1,this[c[b]]=!1);return a},prepareCSS:function(a,b){var c=this;return a.replace(u.cssUrl,function(a,h){return"url("+W(h,c,b)+")"}).replace(u.pseudoFix,function(a,b){return".di-"+b}).replace(u.canvasCss,function(a,b,h){return a+", "+b+".di-canvas"+h}).replace(u.dWidth,"-width:")},prepareNode:function(b){var c=
this,e,g,f,k=[],m=u.head.test(b.tagName),n,r,t,v=function(a,c){c=c||b.ownerDocument.createElement("i");a.parentNode.replaceChild(c,a)};if(m)l(':not(style,link[type="text/css"],link[rel="stylesheet"],meta[charset],meta[name="viewport"])',b).forEach(function(a){a.parentNode.removeChild(a)});else{b.removeAttribute("onload");l("script,meta,input[type=hidden]",b).forEach(function(a){v(a)});l("img[src],img[_da_remove_src]",b).forEach(function(a){(u.js.test(a.src)||2>+a.getAttribute("data-di-width")&&2>
+a.getAttribute("data-di-height"))&&v(a)});l("img,video,audio,input[src],input[_da_remove_src],[poster],[background],[srcset],source",b).forEach(function(a){var b;if(a.srcset||a.getAttribute("srcset"))a.setAttribute("_da_remove_srcset",da(a.srcset||a.getAttribute("srcset"),c)),a.removeAttribute("srcset");f=["src","poster","background"];for(e=0;e<f.length;++e)if(b=("src"!==f[e]||d(a.getAttribute("data-src"))?a.getAttribute(f[e]):a[f[e]])||a.getAttribute("_da_remove_"+f[e]))a.setAttribute("_da_remove_"+
f[e],W(b,c)),a.removeAttribute(f[e])});l("a[href],a[_da_remove_href]",b).forEach(function(a){a.removeAttribute("_da_remove_href");a.href="#"});l("form",b).forEach(function(a){l("input, select, textarea",a).forEach(function(a){a.setAttribute("autocomplete","off");a.removeAttribute("minlength");a.removeAttribute("maxlength");a.removeAttribute("required");a.removeAttribute("pattern");a.removeAttribute("min");a.removeAttribute("max");a.removeAttribute("step");u.invalidInput.test(a.type)&&a.setAttribute("type",
"text")});a.setAttribute("autocomplete","off");a.setAttribute("novalidate","novalidate")});l("[style]",b).forEach(function(a){a.setAttribute("_da_remove_style",c.prepareCSS(a.style.cssText));a.removeAttribute("style")});l("embed,object,noscript,iframe",b).forEach(function(a){f=["src","_da_remove_src","value","type"];if(a.getAttribute("data")){var b="",h=a.getAttribute("type");h&&0===h.toLowerCase().indexOf("image")&&(f.pop(),b=W(a.getAttribute("data"),c));try{a.setAttribute("data",b)}catch(g){}}for(e=
0;e<f.length;++e)a.removeAttribute(f[e]);a.innerHTML=""});if(a._dijstop)return null;l(this.pds,b).forEach(function(a){ta(a)});l("[data-di-id],[data-di-form-track],[data-di-rand],[data-di-width],[data-di-height]",b).forEach(function(a){a.removeAttribute("data-di-id");a.removeAttribute("data-di-form-track");a.removeAttribute("data-di-rand");a.removeAttribute("data-di-width");a.removeAttribute("data-di-height")});l.matches(":not("+this.ufs+")",l.matches(":not([type=submit],[type=reset],[type=checkbox],[type=radio],[type=image],[type=file],[type=button])",
l("input",b))).forEach(function(a){d(a.getAttribute("value"))||a.setAttribute("value",a.value.replace(u.mask,"*"))});l.matches(":not("+this.ufs+")",l("select",b)).forEach(function(a){ta(a);l("option",a).forEach(function(a){d(a.getAttribute("value"))||a.setAttribute("value",a.value.replace(u.mask,"*"))})});l.matches(":not("+this.ufs+")",l("textarea",b)).forEach(function(a){a.setAttribute("data-di-mask","")});l(this.cS,b).forEach(function(a){r=a.getAttribute("data-di-res-id");a.removeAttribute("data-di-res-id");
t=c.canvasList[r];if(!d(t))if(t.tainted)c.tcanvas=!0;else{n=b.ownerDocument.createElement("img");n.className=a.className+" di-canvas";f=["id","width","height"];for(e=0;e<f.length;++e)!d(a[f[e]])&&(n[f[e]]=a[f[e]]);!d(a.getAttribute("_da_remove_style"))&&n.setAttribute("_da_remove_style",a.getAttribute("_da_remove_style"));n.setAttribute("_da_remove_src",t.src||t.content);v(a,n)}});l("svg",b).forEach(function(a){r=a.getAttribute("data-di-res-id");a.removeAttribute("data-di-res-id");t=c.svgList[r];
d(t)?v(a):v(a,c.altClone?xa(t.el):t.el.cloneNode(!0))})}if(a._dijstop)return null;l('link[type="text/css"],link[rel=stylesheet]',b).forEach(function(a){a.setAttribute("_da_remove_href",W(a.href||a.getAttribute("_da_remove_href"),c));a.removeAttribute("href")});l("style",b).forEach(function(a){r=a.getAttribute("data-di-res-id");a.removeAttribute("data-di-res-id");t=c.cssList[r];d(t)?m?a.parentNode.removeChild(a):v(a):(t.tooLarge&&(c.lstyle=!0),t.href?(n=b.ownerDocument.createElement("link"),n.type=
"text/css",n.rel="stylesheet",n.setAttribute("_da_remove_href",t.href),v(a,n)):a.innerHTML=t.content)});if(a._dijstop)return null;b=b.innerHTML;if(!m){for(;g=u.textarea.exec(b);)""!==g[2]&&k.push({k:g[0],v:"<textarea"+g[1]+">**** ****</textarea>"});g=k.length;for(e=0;e<g;++e)b=b.replace(k[e].k,k[e].v);d(this.pdr)||(b=b.replace(this.pdr,sa));!d(this.maskE)&&this.maskE&&(b=b.replace(u.email,Ba));!d(this.maskS)&&this.maskS&&(b=b.replace(u.ssn,sa));b=b.replace(u.cc,qa)}b=b.replace(u.comment,"\x3c!-- c --\x3e");
b=b.replace(u.remove,"");return b=b.replace(u.space," ")},addToPUList:function(a){this.hasFlag(512)&&0>J(a,this.puList)&&(this.puList.push(a),this.puListB.push(a),10<=this.puListB.length&&this.sendProxyUrl())},sendProxyUrl:function(a){this.hasFlag(512)&&this.puListB.length&&(this.postInfo("proxyUrlList",this.puListB,{onExit:a}),this.puListB=[])},getDocType:function(){var a="",c=b.doctype;D(this.jHtml.docType)?c&&(a="<!DOCTYPE "+c.name+(c.publicId?' PUBLIC "'+c.publicId+'"':"")+(!c.publicId&&c.systemId?
" SYSTEM":"")+(c.systemId?' "'+c.systemId+'"':"")+">\n"):a=this.jHtml.docType;return a},getAttributes:function(a){var b,c={},g=a.attributes;a=0;for(b=g.length;a<b;a++)c[g[a].nodeName]=g[a].value||g[a].nodeValue;return c},getHtml:function(){l("img",O()).forEach(function(a){a.setAttribute("data-di-width",a.width);a.setAttribute("data-di-height",a.height)});return{docType:this.getDocType(),htmlAttr:this.getAttributes(b.documentElement),headAttr:this.getAttributes(va()),head:va().innerHTML,bodyAttr:this.getAttributes(O()),
body:O().innerHTML}},prepareHtml:function(a){var b,c,g={};g.head=va();g.body=O();for(b in g)if(g.hasOwnProperty(b)||d(a)||a===b)c=this.altClone||l("video,audio",g[b]).length?xa(g[b]):g[b].cloneNode(!0),this.jPHtml[b]=this.prepareNode(c)},startJourney:function(){if(this.j){var b,e=this,f,g="";f=this.getDateStr();var k;if(d(this.jRate)||0>this.jRate||10<this.jRate)this.jRate=5;this.jIRate=this.jRate;this.pUrl="http://proxy.decibelinsight.net/proxy/";this.hasFlag(512)&&(this.pUrl="http://proxy.decibelinsight.net/da-"+
this.aNum+"/"+this.wId+"/"+f+"/");this.hasFlag(4096)&&(this.rUrl="http://da-"+this.aNum+"-proxy.decibelinsight.net/res/"+this.wId+"/"+f+"/");this.hasFlag(1024)&&(this.pUrlH="http://da-"+this.aNum+"-proxy.decibelinsight.net/hybrid/"+this.wId+"/");this.pUrl=this.pUrl+c.host.toLowerCase()+"/";this.jLT=this.time.getTime();this.isHP=!0;this.jDMP=this.jDMP||new diff_match_patch;this.jDMP.Diff_Timeout=.15;this.loadResList();this.scanResource();this.jHtml=this.getHtml();this.prepareHtml();this.lPHtml={head:this.jPHtml.head,
body:this.jPHtml.body};15E5<this.jPHtml.head.length+this.jPHtml.body.length?(f="413 Request entity too large",this.jRate=0,this.j=!1):f=L({docType:this.jHtml.docType,htmlAttr:this.jHtml.htmlAttr,headAttr:this.jHtml.headAttr,head:this.jPHtml.head,bodyAttr:this.jHtml.bodyAttr,body:this.jPHtml.body});k=e.getParamForReplay();for(b in k)k.hasOwnProperty(b)&&(g+="&"+b+"="+k[b]);e.postInfo("html",f,{imp:!0,extraParam:g});e.sendProxyUrl();setTimeout(function(){e.isHP=!1},500/this.jRate);0<this.jRate&&(a._dijstop=
!1,this.jInt=setInterval(F(this.buildJourney,this),1E3/this.jRate),this.jrInt=setInterval(F(this.scanResource,this),1E3/this.jrRate),this.jfInt=setInterval(F(this.checkformValue,this),100))}},loadResList:function(){if(la){var a=k.getItem("di_res_list");d(a)||(this.resList=pa(a))}},scanResource:function(){var a=this,b=this.getDateStr(),c=this.hasFlag(4096),g,f,k,m,n,r,u;l("style").forEach(function(n){r=!1;k=n.getAttribute("data-di-res-id");d(k)&&(k=M(t()+"_"+e.random()),n.setAttribute("data-di-res-id",
k));g=n.innerHTML||n.textContent;d(g)&&!d(n.sheet)&&(g=aa(n.sheet));m=a.cssList[k];d(g)||!d(m)&&m.innerText===g||(u=g.length,3E4<u&&!l.matchesSelector(n,"[data-di-track]")&&(r=!0,g="/* Style block too large | "+u+" characters */"),f=a.prepareCSS(g,c),m={id:k,innerText:g,content:f,tooLarge:r},f.length>a.jrMin&&c&&(m.name=M(f)+"-"+f.length+".css",m.date=b,m.href=a.rUrl+m.name,a.sendResource(m)),a.cssList[k]=m)});l.matches(":visible",l(this.cS)).forEach(function(c){n=!1;k=c.getAttribute("data-di-res-id");
d(k)&&(k=M(t()+"_"+e.random()),c.setAttribute("data-di-res-id",k));try{f=c.toDataURL("image/png")}catch(g){f="",n=!0}m=a.canvasList[k];if(d(m)||m.content!==f)m={id:k,tainted:n,content:f},!n&&a.hasFlag(4096)&&(m.name=M(f)+"-"+f.length+".png",m.date=b,m.src=a.rUrl+m.name,a.sendResource(m),c.setAttribute("data-di-rand",t())),a.canvasList[k]=m});l("svg:visible").forEach(function(b){k=b.getAttribute("data-di-res-id");d(k)&&(k=M(t()+"_"+e.random()),b.setAttribute("data-di-res-id",k));m={id:k,el:a.altClone?
xa(b):b.cloneNode(!0)};a.svgList[k]=m})},sendResource:function(a){0>J(a.name,this.resList)&&(this.send("resource",a.content,{noBase:!0,extraParam:"&file="+a.name+"&date="+a.date}),this.resList.push(a.name),z("di_res_list",L(this.resList)))},endJourney:function(a){var b;this.j&&(this.clearTimer(["jInt","jrInt","jfInt"]),this.buildJourney(a),this.jBuf.length&&(b=this.getParamForReplay(),b.content=L(this.jBuf),this.postInfo("patch",b,{onExit:a,patchSize:this.jBPS})),this.sendProxyUrl(a),this.jBuf=[],
this.jBPS=0,this.jCur={jE:[],fE:{}},this.jLast={},this.jLT=null,this.lstyle=this.tcanvas=this.lb=this.jCh=!1,this.jSel="",this.pN=this.jC=1)},sendGoal:function(a,b,c,g){var e={};this.hasFlag(2)&&!d(a)&&(e.conid=a,e.conc=d(c)?"":c,e.conv=d(b)||!r(b)?0:b,e.conp=d(g)?this.getPageUrl():g,this.postInfo("goal",e))},sendIntegrationData:function(a,b){!this.hasFlag(2)||d(a)||d(b)||this.postInfo("int",{"int":a,content:L(b)})},sendApplicationError:function(a,b){var c=this,g="";this.hasFlag(64)&&!d(a)&&(b?l(a).forEach(function(a){g=
ha(l.getText(a));d(g)||c.postInfo("applicationerror",{error:g})}):this.postInfo("applicationerror",{error:a}))},sendCustomDimension:function(a,b,c){var g,e={};if(this.hasFlag(2)&&!d(a)){if(K(a)&&!d(a=a.trim())&&!d(b))c&&(b=this.qs[b]),d(b)||(e[a]=b);else if(B(a))for(g in a)!a.hasOwnProperty(g)||d(g.trim())||d(a[g])||(e[g.trim()]=a[g]);!N(e)&&this.postInfo("customdimension",e)}},sendHTTPError:function(a){this.hasFlag(64)&&!d(a)&&r(a)&&this.postInfo("httperror",{error:a})},getLeadId:function(){return"di-"+
this.wId+"-"+this.leadId},getSessionId:function(a){return(!1===a?"":"di-"+this.wId+"-")+this.sId},getPageTime:function(){return this.time.getTime()},getDateStr:function(){return this.time.getUTCFullYear()+"-"+Da(this.time.getUTCMonth()+1)+"-"+Da(this.time.getUTCDate())},updateLead:function(a){var b={};this.hasFlag(2)&&!d(a)&&(d(a.userId)||(this.userId=b.uid=a.userId),d(a.companyName)||(b.comn=a.companyName),N(b)||(this.iProt="https:",this.postInfo("leadinfo",b)))},updateUserId:function(a){this.hasFlag(2)&&
!d(a)&&(this.userId=a,this.iProt="https:",this.postInfo("leadinfo",{uid:a}))},updateLeadScore:function(a){this.hasFlag(2)&&!d(a)&&r(a)&&this.postInfo("leadscore",{lid:this.leadId,score:+a})},trackPageView:function(a,b){var e;this.hasFlag(2)&&(b=b||{},this.initPV&&(this.sendScroll(),this.endJourney(),this.endForm(),this.postInfo("flush")),this.time=new Date,this.eC=this.dC=0,this.tUrl=this.getURL(),d(a)?this.pageUrl.url=this.tUrl.url:(e=c.host,d(e)&&this.hasFlag(1024)&&(e="hybrid"),this.pageUrl.url=
c.protocol+"//"+e+"/"+a.replace(/^\//,"")),this.pageUrl.query=(b.queryString||this.tUrl.query).replace(/^\?/,""),this.pageUrl.hash=(b.fragment||this.tUrl.hash).replace(/^\#/,""),this.pTitle=b.title||this.getPageTitle(),this.pRol=b.role||this.pRol,this.pTax=b.taxonomy||this.pTax,this.postInfo("page",this.pageData(),{imp:!0,callback:F(this.runIntScripts,this)}),this.initPV?(this.startJourney(),this.startForm()):(this.initPV=!0,this.initPageTrack()))},get_da_:function(a){var b,c,g,e;if(d(a))return"";
H(a)||(a=[a]);b=0;for(g=a.length;b<g;b++){c=0;for(e=this.mTag.length;c<e;c++)if(this.mTag[c].name===a[b])return this.mTag[c].content;if(!d(this._da_[a[b]]))return this._da_[a[b]]}return""},get:function(a){var b=this.get_da_(a._da_),c;d(b)&&!d(a.str)&&(la&&(!d(c=k.getItem(a.str))&&(b=c),d(b)&&!d(c=m.getItem(a.str))&&(b=c)),d(b)&&!d(c=Ea(a.str))&&(b=c));if(d(b)&&!d(a._da_e)&&"session"===a.type&&(b=this._da_[a._da_e],!d(b)))return z(a.str,b),b;d(b)&&!d(a._da_e)&&"lead"===a.type&&(b=this._da_[a._da_e],
d(b)||C(a.str,b));return b},indexElements:function(a){var b=t(),c=this;if(this.coll||a)200<b-this.lIT?(A(this.intSel),this.lIT=b):null===this.inTo&&(this.inTo=setTimeout(function(){A(c.intSel);c.lIT=b;c.inTo=null},200))},getSelection:function(){var b,c,e;if(this.j&&a.getSelection){b=a.getSelection();if(b.rangeCount&&(b.getRangeAt?(c=b.getRangeAt(0),e=c.startOffset,c=c.endOffset):D(b.anchorOffset)||(e=b.anchorOffset,c=b.focusOffset),b.anchorNode!==b.focusNode||e!==c)){b=oa(b.anchorNode)+":"+e+"|"+
oa(b.focusNode)+":"+c;b!==this.jSel&&(this.jSel=this.jCur.s=b);return}""!==this.jSel&&(this.jSel=this.jCur.s="")}},resizeEvent:function(){this.lInt=t();this.coll&&(this.vpW=S(a),this.vpH=P(a),this.svT=ia(a),this.svL=ea(a),this.svB=P(a)+this.svT,d(this.fixEl)||d(X(this.fixEl))||(this.fixPos=X(this.fixEl)));return!1},scrollEvent:function(){var b=this,c=ia(a),d=ea(a);this.lInt=t();this.isS||(this.sX=c,this.sY=d);this.isS=!0;clearTimeout(this.sTi);this.sTi=setTimeout(function(){b.isS=!1;b.sX=0;b.sY=0},
100);this.coll&&(this.svT=c,this.svL=d,this.svB=P(a)+this.svT,this.lst!==this.svT&&(c=0-this.lst,this.lst=this.svT,c+=this.lst,this.mY=e.round(this.mY+c)),this.lsl!==this.svL&&(c=0-this.lsl,this.lsl=this.svL,c+=this.lsl,this.mX=e.round(this.mY+c)));return!1},sendScroll:function(a){for(var b in this.hvDur)this.hvDur.hasOwnProperty(b)&&500>this.hvDur[b]&&2===b.split(",").length&&delete this.hvDur[b];this.postInfo("scrollinfo",{ft:this.focusTime,scroll:this.scDur,hover:this.hvDur},{onExit:a});this.focusTime=
0;this.scDur={};this.hvDur={};this.srC=0},onExit:function(b){this.coll&&!this.lSS&&(this.lSS=!0,this.sendScroll(!0),this.endJourney(!0),this.endForm(!0),this.postInfo("exit"));b=b||a.event;if(!b)return""},pointerDown:function(b){b=b||a.event;this.lInt=t();if(this.coll){var c,d,g=b.touches;b=this.makePointerEvent(b);b.p&&b.t&&this.pT++;b.m?(c=!0,d=!1):b.t&&g?(c=1===g.length,d=2===g.length):b.p&&b.t&&(c=1===this.pT,d=2===this.pT);this.isS||(c?(this.cC=!0,this.tTi=t(),this.tX=b.x,this.tY=b.y):d&&!b.p&&
(this.cP=!0,this.cC=!1,this.pDs=e.sqrt(e.pow(g[1].pageX-g[0].pageX,2)+e.pow(g[1].pageY-g[0].pageY,2))))}},pointerCancel:function(b){b=b||a.event;this.coll&&(b=this.makePointerEvent(b),this.cC=!1,b.p&&b.t&&this.pT--,this.tY=this.tX=null,this.tTi=0,this.cP=!1,this.pDe=this.pDs=0)},pointerMove:function(b){b=b||a.event;this.lInt=this.lHov=t();if(this.coll){var c=this.makePointerEvent(b);b=b.touches;c.m&&(this.mX=c.x,this.mY=c.y,this.hEl=this.getClElID(c.target));this.cP&&c.t&&!c.p&&(this.pDe=e.sqrt(e.pow(b[1].pageX-
b[0].pageX,2)+e.pow(b[1].pageY-b[0].pageY,2)))}},contextMenu:function(b){b=b||a.event;this.coll&&0<this.tTi&&!d(this.tX)&&!d(this.tY)&&(this.setClickData({x:this.tX,y:this.tY,t:!1},b),this.sendClick(this.getClElID(b.target||b.srcElement)),this.clearClickData())},pointerUp:function(b){b=b||a.event;this.lInt=t();if(this.coll){var c,f=this.makePointerEvent(b);if(this.cC)if(5>e.abs(this.tX-f.x)&&5>e.abs(this.tY-f.y))"HTML"!==f.target.tagName&&(!this.isS||5>e.abs(this.sX-ia(a))&&5>e.abs(this.sY-ea(a)))&&
(this.setClickData(f,b),this.pGoal&&this.processClick(f.target),this.sendClick(this.getClElID(f.target)));else if(f.t&&!d(this.tX)&&!d(this.tY)){b=f.x-this.tX;var g=f.y-this.tY;500>=t()-this.tTi&&(100<=e.abs(b)&&e.abs(b)>=e.abs(g)?c=0>b?"l":"r":100<=e.abs(g)&&e.abs(g)>=e.abs(b)&&(c=0>g?"u":"d"),c&&(this.jCur.tE=c))}this.cP&&f.t&&!f.p&&(1>this.pDs/this.pDe?c="i":1<this.pDs/this.pDe&&(c="o"),c&&(this.jCur.tE=c),this.cP=!1);this.clearClickData();f.p&&f.t&&this.pT--;this.getSelection()}},setClickData:function(a,
b){this.mX=a.x;this.mY=a.y;this.clX=a.x;this.clY=a.y;a.t?this.clT=3:d(b.which)?this.clT=2>b.button?0:4===b.button?1:2:this.clT=2>b.which?0:2===b.which?1:2},clearClickData:function(){this.cC=!1;this.tY=this.tX=null;this.tTi=0;this.cP=!1;this.pDe=this.pDs=0},makePointerEvent:function(c){var d={};d.p=-1<c.type.indexOf("pointer");d.target=c.target||c.srcElement;d.p?(d.t="touch"===c.pointerType||2===c.pointerType,d.m=!d.t):(d.t=-1<c.type.indexOf("touch"),d.m=-1<c.type.indexOf("mouse"));d.m||d.p?D(c.pageX)?
(d.x=c.clientX+ea(a)-b.documentElement.clientLeft,d.y=c.clientY+ia(a)-b.documentElement.clientTop):(d.x=c.pageX,d.y=c.pageY):d.t&&(d.x=c.changedTouches[0].pageX,d.y=c.changedTouches[0].pageY);d.x=e.round(d.x);d.y=e.round(d.y);return d},getClElID:function(a){if(d(a)||d(a.getAttribute))return"";var b=a.getAttribute("data-di-id");d(b)&&(b="",u.body.test(a.tagName)||u.html.test(a.tagName)||(b=this.getClElID(a.parentNode)));return b},sendClick:function(a){var b=new Date,c=this.fixPos,d=this.clX,f=this.clY,
k=this.clT,l=d,m=f;r(d)&&r(f)&&(r(c.left)&&r(c.top)&&(d=e.round(d-c.left),f=e.round(f-c.top)),a={clx:d-d%3+1,cly:f-f%3+1,clt:this.clT,ceid:a},b={x:d,y:f,t:k,ti:b.getTime()},2<e.abs(this.tXYT.x-b.x)||2<e.abs(this.tXYT.y-b.y)||b.ti-this.tXYT.ti>(b.t!==this.tXYT.t?1E3:250))&&(this.tXYT=b,this.jCur.cX=l,this.jCur.cY=m,this.jCur.cT=k,this.postInfo("click",a),this.smo||(this.indexElements(),this.formIndex()))},getiURL:function(a,b){var c="";!1!==b.counter&&(c="&dc="+ ++this.dC);"file:"===this.iProt&&(this.iProt=
"https:");return this.iProt+this.iUrl+"?type="+a+"&wid="+this.wId+"&sid="+this.sId+"&pu="+ja(this.pageUrl.url)+"&qu="+ja(this.pageUrl.query)+"&fr="+ja(this.pageUrl.hash)+"&pvid="+this.time.getTime()+(b.extraParam||"")+(this._da_.da_anonymiseIP?"&dnt=1":"")+c+"&tz="+this.tZ+"&dv=1&v=3.24.0"},pageData:function(){var b=B(a.performance)&&B(a.performance.navigation)?"&navtype="+a.performance.navigation.type:"&navtype=0",c=this.jSupB?"":"&ub=1",e;la&&(this.pC=1,e=k.getItem("di_page_counter"),!d(e)&&(this.pC+=
+e),z("di_page_counter",this.pC));b="lid="+this.leadId+"&uid="+this.userId+"&pc="+this.pC+"&tc="+this.tId+"&lan="+this.lan+"&je="+this.java+"&fv="+this.fVer+"&srw="+this.sResW+"&srh="+this.sResH+"&vpw="+this.vpW+"&vph="+this.vpH+b+c+"&ptax="+ja(this.pTax)+"&pr="+ja(this.pRol)+"&pt="+ja(this.pTitle)+"&ref="+ja(this.refUsed?"":this.ref);this.refUsed=1;return b},postInfo:function(a,b,c){var d=t();c=c||{};this.coll&&(c.imp?this.send(a,b,c):"exit"===a?(this.send("multi",L(this.pB),{async:!1,extraParam:"&ex=1"}),
this.resetPostBuffer()):"flush"===a?(this.send("multi",L(this.pB)),this.resetPostBuffer()):(this.pB.push({type:a,data:b,offset:e.floor((d-this.getPageTime())/1E3)}),this.pBPS+=c.patchSize||0,!c.onExit&&(10<=this.pB.length||1E4<this.pBPS||1E4<d-this.pBLT)&&(this.send("multi",L(this.pB)),this.resetPostBuffer())))},resetPostBuffer:function(){this.iProt=c.protocol;this.pB=[];this.pBPS=0},send:function(b,c,k){k=k||{};k.key=k.key||"k:"+(t()+e.random());k.data=null;k.dataLength=0;k.type=b;b=this.getiURL(b,
k);if(!d(c)&&(k.data=c,k.dataLength=c.length,!k.noBase))try{c=k;var g;var l=k.data;g=a.btoa?"DIB64;"+a.btoa(unescape(encodeURIComponent(l))):l;c.data=g}catch(m){}this.pBLT=t();u.boolTrue.test(Q.getAttribute("di-heatmap"))||(f.sendBeacon&&!1===k.async?f.sendBeacon(b,k.data)||(k.retryCode="beaconError",k.async=!0,this.addAjaxBuf(b,k)):this.bufferAndSend(b,k))},bufferAndSend:function(a,b){var c=this;!1===b.buffer?ka(a,b):(this.addAjaxBuf(a,b),ka(a,b,function(a){c.removeAjaxBuf(b.key);b.callback&&b.callback(a)},
function(a){c.setRetryAjaxBuf(b.key,a)}))},addAjaxBuf:function(a,b){this.aBuf[b.key]={url:a,options:b};b.storFailed=!C("di_ajax",L(this.aBuf))},removeAjaxBuf:function(a){delete this.aBuf[a];C("di_ajax",L(this.aBuf))},setRetryAjaxBuf:function(a,b){var c=this.aBuf[a];c.options.retry=!0;c.options.retryCode=b;this.aBuf[a]=c;C("di_ajax",L(this.aBuf));d(this.aBufI)&&(this.aBufI=setInterval(F(this.sendABuf,this),500))},getInitAjaxBuf:function(){var a,b,c;if(la&&(b=m.getItem("di_ajax"),!d(b))){c=pa(b);for(a in c)c.hasOwnProperty(a)&&
(b=c[a].options,b.retry=!0,b.crossPage=!0,this.addAjaxBuf(c[a].url,b));this.aBufI=setInterval(F(this.sendABuf,this),500)}},sendABuf:function(){var a,b,c,d=!1;for(a in this.aBuf)!d&&this.aBuf.hasOwnProperty(a)&&(c=this.aBuf[a].options,c.retry&&(d=!0,c.c=(+c.c||0)+1,c.c<this.aTry?(c.retry=!1,b=this.aBuf[a].url,c.retryCode&&(b+=(0<b.indexOf("?")?"&":"?")+"retryCode="+c.retryCode),c.crossPage&&(b+=(0<b.indexOf("?")?"&":"?")+"crossPage=1"),this.bufferAndSend(b,c)):(this.send("meta",L({failedReq:{type:c.type,
size:c.dataLength,reason:c.retryCode,crossPage:!!c.crossPage,storFailed:!!c.storFailed}}),{buffer:!1}),this.removeAjaxBuf(c.key))));d||this.clearTimer(["aBufI"])},clearTimer:function(a){for(var b=0,c=a.length;b<c;b++)clearInterval(this[a[b]]),this[a[b]]=null},Sizzle:l,isEmpty:d,isEmptyObject:N,isUndefined:D,isNumber:r,isString:K,isObject:B,isArray:H,trim:Ca,trimnlb:ha,isFunction:x,setSS:z,setLS:C,addEvent:w,offset:X,getStyle:ma,extend:ga,width:S,height:P,scrollTop:ia,scrollLeft:ea,closest:fa,indexInParent:ba,
inArray:J,getCookie:Ea,getXPath:oa,proxy:F,ajax:ka,hash:M};Array.prototype.forEach||(Array.prototype.forEach=function(a,b){var c,d,e,f;if(null===this||void 0===this)throw new TypeError(" this is null or not defined");e=Object(this);f=e.length>>>0;if("function"!==typeof a)throw new TypeError(a+" is not a function");1<arguments.length&&(c=b);for(d=0;d<f;){var k;d in e&&e.hasOwnProperty(d)&&(k=e[d],a.call(c,k,d,e));d++}});za()})(window,document,document.location,navigator,Math,window.sessionStorage,
window.localStorage,window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver,_da_Sizzle);